.pre-commit-config.yaml
Config change to disable "auto-fix" of pre-commit hooks on repo. This is to prevent discrepancies between developers' pushed code and changes made remotely upon push (forces devs to fix their problems locally before push)
Added autofix disable flag to pre-commit config
Tested with deliberate commit with black error, screenshot from Github:
=> Disable pre-commit autofix

core/validation/failures.py
https://trello.com/c/3vooZ6ha/211-bug-excel-row-index-display-to-user
Excel is 1-indexed and uses the top row as a header. This meant that 0-indexed row index's in the error messages would not make sense to an Excel user. This change increments all row indexes returned in error messages by 2 to account for this.
- [NA] Unit tests and other appropriate tests added or updated
=> [#PAB-211] fix user facing validation error row index

core/controllers/ingest.py, core/validation/README.md, core/validation/casting.py, core/validation/failures.py, core/validation/validate.py, tests/validation_tests/test_casting.py, tests/validation_tests/test_validate.py
https://trello.com/c/0aP9Yqyb/231-separate-casting-ingested-data-types-to-the-schema-and-validation
Split out type casting from the validation function to separate concerns and simplify testing and extension.
=> [#PAB-231] split out type casting from validation

copilot/.workspace, copilot/data-store/addons/data-store-cluster.yml, copilot/data-store/manifest.yml
In preparation for the Pen Test, we need to re-configure the API to be a [Backend Service](https://aws.github.io/copilot-cli/docs/manifest/backend-service/), so it is not exposed on the public internet.
This also changes the parent 'app' name to post-award to be in better keeping with copilot conventions
Should deploy successfully after merge
=> PAB-297: update copilot app to deploy as a backend service

core/cli.py, core/const.py, core/controllers/download.py, core/controllers/examples.py, core/controllers/ingest.py, openapi/api.yml, requirements-dev.txt, requirements.in, requirements.txt, tests/controller_tests/test_api_status.py, tests/controller_tests/test_download.py, tests/controller_tests/test_ingest.py
https://trello.com/c/wBlZvwpn/362-create-data-as-file-api-endpoint
Adds an endpoint that returns some data in either xlsx or json format. The data returned is just example data for now.
=> [#PAB-362] add download endpoint

.github/workflows/deploy.yml
Now we are using Postgres which persists state we need to drop tables in order to pick up schema changes between deployments Note: we will change to use proper migrations prior to production deployment
Should deploy successfully on merge
=> PAB-297: drop db prior to seed

core/cli.py
[#PAB-297]
Bugfix, database was not dropped due to an open (cached) transaction causing a "table-lock". One -liner to fix this in the `flask drop` cli command.
=> [#PAB-297] bugfix to "flask drop" CLI command

copilot/environments/overrides/README.md, copilot/environments/overrides/cfn.patches.yml
Patch Copilot environment to fix issue raised in pen test
Host should not be accessible using older SSL protocols
see diff:
```
~ Description: CloudFormation environment template for infrastructure shared among Copilot workloads. -> CloudFormation environment template for infrastructure shared among Copilot workloads using AWS Copilot with YAML patches.
~ Resources:
~ CloudFrontDistribution:
~ Properties:
~ DistributionConfig:
~ ViewerCertificate:
(1 unchanged item)
~ - (changed item)
~ MinimumProtocolVersion: TLSv1 -> TLSv1.2_2021
(1 unchanged item)
```
=> BAU: override default minimum protocol version

core/db/entities.py, core/extraction/towns_fund.py
Transform PSI ready to load into DB ` PrivateInvestments`
Transform and combine Project and programme risks, into `RiskRegister`
Tweak DB table to allow data for cancelled project, as per example (data rows are empty, but cancellation summary provided in risk name column)
=> [#PAB-332] Transform round 3 PSI and Risk Register

core/extraction/round_one.py, tests/controller_tests/test_integration.py
Added ingestion of programme progress, organisation ref, and funding questions. I have also added a function to get Programme IDs for programme tables.
TO DO:
- update function for getting project id's to match round 2 & 3
- ingest outcome data
- consider column order of returned dataframes
=> [#PAB-390] added ingestion of programme progress, organisation ref, funding qs

core/controllers/ingest.py, tests/controller_tests/test_ingest.py
BAU_
Previous submission id generation is not working with Postgres due to casting problems between pipeline and postgres (postgres can't adapt type "numpy.int64" - Pandas is outputting this numpy type)
Casting the param to python int before the query fixed it.
Needs testing on Docker - run compose, try and ingest data / run flask seed CLI command on data-store docker container
=> FIX: Fix submission query: invalid input types

.github/workflows/run_command.yml
BAU: Add Run Command workflow
This is useful to be able to perform ad-hoc tasks that happen outside of a commit event
Will be used for some initial admin tasks e.g. clearing down test database.
=> PAB-400: Add Run Command workflow

core/controllers/get_filters.py, openapi/api.yml, openapi/components.yml, tests/controller_tests/test_filters.py
https://trello.com/c/qT7fuTec/427-be-endpoint-list-of-financial-periods-covered-by-the-data
Adds the `/reporting-period-range` endpoint that returns the first reporting period start date and the last reporting period end date in the Submission table.
=> [#PAB-427] reporting period range endpoint

core/util.py, tests/test_postcodes.py
If user leaves postcode field blank transform gives a weird error when regex tries to run on np.nan (as it's from pandas). 
Handle this case and return empty list.
(NOTE: postcode aka locations field should not actually be nullable on DB, but that's a separate validation issue)
=> BAU_ FIX: blank postcode type errors

core/const.py
Added final 3 Output category lookups as "mandatory"
3 new rows added to constants dict
=> BAU_ FIX: Added Mandatory category lookups

core/db/entities.py
DB table Funding's unique constraint was too tight to allow all valid combinations in. Added "secured" to the index, to allow multiple rows with the same project, funding source and funding name, differentiated only by "secured".
Added "secured" to unique index on Funding
=> BAU_ FIX: expand unique index on Funding

.github/workflows/deploy.yml
Fixes after #116 
`task` did not work as does not have access to the database credentials. Use `svc exec` as an interim solution until we can address TODO.
Should successfully run migration following merge
=> PAB-400: fixes to pipeline

core/extraction/towns_fund.py
Rows with outcome "*** ORIGINAL***" were being misused in the form to mean no entries. 
Potentially this one could be selected by accident also.
This is not intended as a selectable outcome, removed these rows on ingest
=> BAU_ FIX: Strip rows with invalid entry from Outcomes

core/extraction/towns_fund.py, core/validation/validate.py, core/validation_schema.py
Fixes validation issue caused by duplicated pandas dataframe indexes from ETL stage. 
Can test by ingesting the Margate submission - before this it would fail on a runtime error during ingestion but the expected behaviour is that it returns validation failures.
=> [BAU_FIX] fix outcome ETL and validation

core/extraction/towns_fund.py
Ingest couldn't match project names to ID's if the project name contained a colon ":", resulting in non-nullable ID failures during validation. This change manages this scenario.
This can be tested by attempting to ingest the `TF_Reporting_Template_(v3.0)_-_TD_-_CASTLEFORD_-_080623.xlsx` ingest ss. This was previously returning lots of validation errors but now passes and ingests.
=> [BAU_FIX] r3 ingest support for projects with colons in the name

copilot/data-store/manifest.yml
* Boosted from .25 of a vCPU to 1 vCPU
* Boosted from 512 MB to a minimum of 2GB
These values are directed from
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
+ref: 468
+semver: minor
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ N/A ] README and other documentation has been updated / added (if needed)
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
=> Updating the cpu and memory requirements

db/migrations/versions/004_alter_field_nullabilities.py
Migration name was over 32 char limit set by alembic, so crashed out when building
=> BAU_ Fix: Migration Name too long

app.py, copilot/data-store/manifest.yml
Add Sentry integration to alert on exceptions, using existing functionality in utils library.
Have tested manually locally. Will not cause any changes locally unless you have `SENTRY_DSN` env var set.
=> PAB-306: Add sentry integration

.github/workflows/deploy.yml
Adds git sha env var
This is useful for debugging and propagates to the healthcheck and to sentry e.g.
```
{"checks":[{"check_flask_running":"OK"}],"version":"b8adfde5ed318928227274a93eef295520755e5d"}
```
Tested by deploying branch to Code env with branch deploy
=> PAB-306: set git sha as env var

.github/workflows/deploy.yml
Previously concurrency restriction was global, it should be environment specific, now we're deploying to test and prod.
Can test post-merge
=> PAB-304: make concurrency per-environment

app.py
keep connection alive as should enable keep-alive on long running request
Theory is connections were timing out as we weren't sending a Keep-Alive on the long running requests, changing this setting updates this by proxy as described in: https://stackoverflow.com/a/10528211
Have tested on test environment and appears to have fixed downloads
=> BAU: set protocol version to HTTP/1.1

.github/workflows/deploy.yml, scripts/migration-task-script.sh
Previously we were running the migrations post-deploy. This was suboptimal in a number of ways:
* Logs not visible 
* Failed migration will not fail CI
* App will be running new version of code if migration fails
* Possible race condition between app code being deployed and migration being applied.
This approach fixes the above issues by running the migrations as a standalone task in a step before the deploy.
See related discussion in: https://github.com/aws/copilot-cli/issues/4989
Tested by deploying branch: https://github.com/communitiesuk/funding-service-design-post-award-data-store/actions/runs/5379096280/jobs/9759839271
=> PAB-306: run migration as task

.github/workflows/deploy.yml
It appears that task does not rebuild the image, as such migrations need to run after the deploy and be backwards compatible
Can test post merge
=> FIX run migrations after deploy

core/const.py, core/controllers/ingest.py, core/extraction/towns_fund.py, core/validation/failures.py, core/validation/initial_check.py, tests/validation_tests/test_pre_checks.py
Added feature to validate file before transformations occur. 
These checks are intended to ensure the following:
- Form version must be: “Town Deals and Future High Streets Fund Reporting Template (v3.0)” → Sheet 1A, column B8
- Reporting period MUST be round 3. Date input string can be mapped to rounds using the dict in core.extraction.towns_fund.extract_submission_details. It would be worth refactoring the code to have this lookup dict in constants folder since it’s being re-used.
- There must be a valid answer provided for sheet 2, Section A, Question A1 (fund type) → if left blank or “< Select >” then ingest will break.
- As previous point but with A2 (place name)
For manual testing, the user must attempt to ingest both a …
=> [#PAB-457]: add initial pre transformation validation

core/controllers/get_filters.py, tests/controller_tests/test_filters.py
https://trello.com/c/wr8jrP7N/17-organisation-filter-on-hambleton-district-council-returns-no-data
Modifies the organisation endpoint to only return organisations referenced by at least one programme. The organisation table itself can not be trusted as the source because we currently ingest unreferenced organisations & organisations can be left unreferenced if re-ingestion with different source data occurs.
=> [FIX] org endpoint only returns orgs referenced by at least one prog

core/const.py
https://trello.com/c/WmTxlOpQ/14-bug-production-outcome-filter-issue
Fixes hard coded mapping used at ingest to remove a trailing space adding a seemingly duplicate outcome category to the database. This will fix future ingests but we'll need to update the live dim data.
=> [FIX] remove trailing space from outcome category mapping for culture

copilot/environments/overrides/cfn.patches.yml
In order to handle slow responses from the API to large download queries we need to increase this timeout
This codifies a change that was previously made manually
Has been deployed locally to test, will deploy to production post-merge.
=> PAB-484: Set 60 second origin timeout

core/const.py, core/extraction/round_two.py
Transformation for footfall outcomes. This concatenates the dataframes for outcomes and footfall outcomes.
Also small modifications to the function for attaching a project id to outcomes.
Please note that the subset used for testing Round 2 will produce an empty dataframe for footfall outcomes. This is because all of the rows for footfall in the subset are effectively null. For this reason, it is advisable to test with the full dataset.
=> Transform Round 2 Footfall

core/extraction/round_two.py, tests/extraction_tests/test_historical_extraction.py
Removes excluded projects from R2. 
Also created a unittest in a new file, test_historical_extraction.py, which can be used to test future modifications to R1/R2 extraction.
=> [#PAB-566]: remove excluded projects from R2

Dockerfile
Requests were timing out on the gunicorn side, curtailing long running ingest tasks. Bumping this timeout solves the immediate issue, although we should also look at query optimisations
Round 1 ingest should work after deployment.
=> BAU FIX: bump timeout

.gitignore, core/extraction/round_two.py, tests/controller_tests/test_integration.py
Reference tables for Outputs & Outcome added.
Gitignore + testing has been updated to reflect the master sheets now used for Round 2 ingestion.
Set breakpoint at appropriate point and inspect the "Outputs_Ref" and "Outcomes_Ref" dataframes.
=> Round 2: Outputs & Outcome refs

.github/workflows/deploy.yml
Previously it was difficult to see what version was being deployed to environments
This adds a `run-name` attribute including the branch, environment and SHA which is visible in github actions 
Have tested by running workflow against branch with these changes
=> BAU: add run name to differentiate task runs

scripts/batch_ingest.py
filter out non excel files
This will filter out non-excel files from the folder e.g. metadata files added by the OS.
Add a non-excel file in target folder. Should be filtered out when running script
N/A
=> BAU FIX: filter out non excel files

core/controllers/download.py, tests/controller_tests/test_download.py
https://trello.com/c/dq3Y7Cgn/575-add-timestamp-to-data-extract-filename
The download filename (either JSON or XLSX) is changed from download.extension to the format download-yyyy-mm-dd-hhmmss.extension
The format depcited in the above ticket includes spaces and colons , however I thought it would be best to leave these out of the filename and instead used hyphens. This can be updated to use spaces if neccessary (but colons and slashes are not permitted).
Changes can be seen in the output file after running download
=> Update filename to include timestamp

.pre-commit-config.yaml
Configures `isort` to use a configuration that doesn't conflict with black
=> [BAU] use isort black profile to prevent pre-commit conflict

copilot/environments/overrides/cfn.patches.yml
Increase cloudfront timeout
Will deploy manually and confirm in AWS console
=> FMD-46: Increase cloudfront timeout to 120 seconds

core/controllers/ingest.py, openapi/components.yml, tests/controller_tests/test_ingest.py
Send response from ingest in JSON format to be in parity with the responses from bad ingests with validation errors.
Sucsessful response is:
```
{
"detail": "Spreadsheet successfully uploaded",
"status": 200,
"title": "success",
}
```
=> BAU: added JSON sucsessful upload response

core/const.py, core/validation/failures.py, tests/validation_tests/test_failures.py
Failure to select an output or outcome left the unit of measurement field blank. This resulted in it being picked up as a null failure, when in actuality the issue is an enum failure with the output or outcome. Changed output and outcomes validation so that the fields are treated as enums, and removed null checks for unit of measurement.
=> [SMD-65]: outputs and outcomes edgecase validation

copilot/environments/overrides/cfn.patches.yml
Sister PR to: https://github.com/communitiesuk/funding-service-design-post-award-data-frontend/pull/60
Increase Cloudfront timeout to match gunicorn timeout on frontend
Will deploy change on merge
=> FMD-46: Increase cloudfront timeout to 180 seconds

config/envs/default.py, core/const.py, core/controllers/ingest.py, core/validation/failures.py, core/validation_schema.py, openapi/components.yml, tests/validation_tests/test_failures.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140/backlog?view=detail&selectedIssue=SMD-85&issueLimit=100
- Adds ability to request ingest for Round 4
- Adds a validation schema for Round 4 that enforces Round 4 validation requirements ([see this](https://communities-govuk.slack.com/files/U04V6KQCNCU/F05P7MMASHK/image.png)).
- Adds more `NonNullableConstraintFailure` support for additional validation scenarios added for Round 4
NOTE: This adds the concept of a Round 4 submission - however, this is purely for validation at the moment. It will still use the Round 3 transformation and ingest logic. Once we have a new Round 4 template, transformation and ingest will also need updating.
=> [SMD-85] Enable Round 4 ingest request and validation

app.py, core/const.py, core/errors.py, core/validation/failures.py, tests/validation_tests/test_failures.py
Added error for wrong types including dates, and numbers usually input incoractly as text. Often simply the unit e.g m^2 is appended to the number.
These errors occur on sheets: Program Progress, Funding Profiles, PSI, Project outputs, Outcomes
=> [SMD-39] Implement WrongTypeFailure UC messages

core/validation/failures.py, tests/validation_tests/test_failures.py
Add user centered error component for Non-unique composite key failure. This error occurs when users specify duplicate funding sources, project outputs, outcomes or risks.
this commit includes a change to the failure message serialisation to ignore duplicate messages and a refactor of all the failure messages to be based solely on the to_user_cetered_components method.
=> [SMD-38] Implement NonUniqueCompositeKeyFailure

core/validation/specific_validations/towns_fund_round_four.py, tests/validation_tests/test_tf_r4_specific_validations.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?selectedIssue=SMD-112
Projects that state multiple locations, must also provide a value for the "GIS Provided" column. This is context specific and so sits outside of the schema validation stage.
=> [SMD-112] TF Round 4 validation - GIS provided required

core/extraction/towns_fund.py, tests/extraction_tests/test_round_three_extraction.py
PR to fix bug raised in: https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?assignee=712020%3A604bc6cd-3120-45eb-939d-28f261742d7b&selectedIssue=SMD-103
Users could enter null values for a project in outcomes because we dropped all nulls in the Relevant Project(s) column before checking to see if the project was valid or not. 
For footfall outcomes, as all of the Indicator Names are pre-populated, it is not possible to check for nulls, but we can continue to check for invalid projects. 
=> BAU: bug fix for null projects in outcomes

core/const.py, core/extraction/towns_fund.py, tests/extraction_tests/resources/mock_sheet_data/funding_profiles_mock.csv, tests/validation_tests/test_failures.py
Fixed to bugs discovered in QA
1. Funding progiles tab, Other funding sorces: duplicate funding source names are not picked up if one has a trailing whitespace
2. Risk register tab: app was crashing becasue of a key error if Risk owner column was left blank this was was occuring in the non_nullable failure message method
=> [SMD-38] QA bug fixes

core/db/queries.py, tests/conftest.py, tests/db_tests/test_queries.py, tests/serialisation_tests/test_serialisation.py
https://dluhcdigital.atlassian.net/browse/FMD-56
Programme level tables were getting duplicated data in the data extract due to incorrect joins. Namely, data from other rounds was showing up against every row of programme related data, but with the incorrect submission etc.
- Add tests to isolate the failures
- Changed programme level joins to join on Submission
- For specific cases of tables that join on project OR programme (RiskRegister and OutcomeData), the programme part of the conditional join changed to be a further nested conditional join on submission only when there is no project_id.
- Refactored some query tests that were becoming obsolete / hard to maintain
Test downloading extract data from UI. For projects with data from multiple rounds, check the project data tabs don't …
=> [FMD-56] Fix programme level joins

core/const.py, core/util.py, core/validation/failures.py, core/validation/specific_validations/towns_fund_round_four.py, tests/validation_tests/test_failures.py, tests/validation_tests/test_tf_r4_specific_validations.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?selectedIssue=SMD-144
as part of story:
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?selectedIssue=SMD-69
- Funding Source wasn't being validated against previously. 
- These changes enable enum validation on the Funding Source column found on the Funding tab for Round 3 and 4.
- This has been implemented as a context specific validation rather than using the schema driven validation code because there are hardcoded sections of the spreadsheet that use "Towns Fund" as a "Funding Source Type" that is forbidden in the "Funding Source" column in the "Other Funding Sources" section. This means that if it was implemented using the schema then users could incorrectly enter "Towns Fund" as a …
=> [SMD-144] TF Round 4 validation - Funding Source dropdown validation

core/const.py, core/serialisation/data_serialiser.py, tests/serialisation_tests/test_serialisation.py
https://dluhcdigital.atlassian.net/browse/FMD-13
Corrects the spelling of OutputsRef to OutputRef. The tests have also been updated and running as normal.
If you check the data extract after clicking download, the spelling on the tab should be updated.
=> FMD-13 update spelling on OutputRef field

core/validation/specific_validations/towns_fund_round_four.py, tests/validation_tests/round_four_specific_validations/mock_data.py, tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py
Validation for Review & Sign-Off section. Checks that Name, Role, and Date are not empty or null. 
Does not validate images for signatures, which will be addressed in a separate PR.
=> [SMD-81]: validate sign-off no images

core/controllers/ingest.py, core/validation/failures.py, core/validation/initial_check.py, tests/validation_tests/test_failures.py, tests/validation_tests/test_pre_checks.py
A user can only submit for the places within their local authority's remit. When a user submits their returns, a tuple of place names is sent to the data store. The pre-transformation checks inspect the place name of the submission form and compare it to the tuple of place names the user is authorised to submit for. If the user is not authorised to submit for the place name, a PreTransFormationFailure is raised.
=> [SMD-156]: backend authorisation

core/extraction/towns_fund_round_three.py, core/extraction/utils.py, core/validation/failures.py
Fixed an edge case where if users entered a numeric character as a funding source name it would be cast to NA when string methods were applied to it by first converting the colum with astype(str)
Seperate refactor of a small method to cast to a string and join with ', ' in failures.py as  was recomended a few days ago
=> BAU: fix more descriptive error messages by casting to string

core/const.py, core/extraction/towns_fund_round_four.py, core/extraction/towns_fund_round_three.py, core/extraction/utils.py, core/validation/failures.py, tests/extraction_tests/resources/assertion_data/round_four/risks_expected.csv, tests/extraction_tests/test_round_four_extraction.py, tests/extraction_tests/test_utils.py, tests/validation_tests/test_failures.py
https://dluhcdigital.atlassian.net/browse/SMD-67
- modifies Round 4 ingestion to extract risk data regardless of if it has a null Risk Name
- adds validation support to catch this scenario
=> [SMD-67] risk ingest without risk name

core/validation/failures.py, core/validation_schema.py, tests/validation_tests/test_failures.py
Adds three new fields to the round 4 validation schema to pick up non-nullable columns which refer to spreadsheet row that must be filled with zeros instead of being left blank.
=> [SMD-64] Funding-Profile-Validation-Ensure-Filled-Cells

app.py, config/envs/default.py, core/controllers/ingest.py, core/exceptions.py, core/extraction/__init__.py, core/extraction/towns_fund_round_three.py, core/handlers.py, core/validation/__init__.py, core/validation/initial_check.py, core/validation/validate.py, core/validation_schema.py, openapi/components.yml, scripts/validate.py, tests/controller_tests/test_ingest.py, tests/extraction_tests/test_round_three_extraction.py, tests/validation_tests/test_validate.py
This refactor expanded to cover more files than I had planned.. I originally wanted to just remove the redundancy that using both source_type and reporting_round created. The additional changes tidy things up though and make our approach to configuring the different components per reporting round more consistent - making ingest easier to follow. Obviously if we move to multiple funds this will have to change to incorporate that, but the last system didn't do that anyway.
- ingest now calls pre_tranformation_checks, extract_data, and validate_workbook functions with the workbook and the reporting round
- each functions are located in their various packages
- "source type" has been removed and replaced solely with "reporting_round" - it had some 1-1 mappings already and having both was …
=> [BAU] refactor ingest calling components

core/extraction/towns_fund_round_four.py, core/extraction/towns_fund_round_three.py, core/validation/initial_check.py, core/validation_schema.py, scripts/batch_ingest.py, tests/extraction_tests/test_round_four_extraction.py, tests/extraction_tests/test_round_three_extraction.py
Allow full re-ingest of Round 3 data
Draft PR because we are down to just 4 validation errors
This PR is more like several small bug fixes in one.
Changes:
- towns_fund_round_3.py 292: Some LA's added comments outside the area for inputing data, this created an extra column error so I tightened up the extraction for this sheet.
- towns_fund_round_3.py 883: Some round 3 data is missing projects assigned to outcomes. These rows are dropped (We should not carry this behaviour over to round 4) one test is ignored because and will be deleted.
- round 3 data has a large number of composite key validation errors where data has been previously ingested therefore this constraint is completely relaxed for round 3
Issues remaining:
- One LA has a Dropdown error: "Events programme" is in the cell …
=> [SMD-188] Fix failing round 3 file ingests

copilot/environments/test/manifest.yml
In order to create a future network connection between pre-award and post-award apps. We need to add the shared VPCs to allow them to communicate.
Note: this is deliberately draft until we're ready to switch over to the other AWS account 
Can verify using AWS console
=> FMD-38: add shared VPCss

copilot/data-store/addons/data-store-failed-files.yml, copilot/data-store/addons/data-store-file-assets.yml
Previously the S3 integration would have failed on AWS as the env vars did not match those the app expected e.g. in: https://github.com/communitiesuk/funding-service-design-post-award-data-store/blob/ef0bc0ce26d4144937dcee0648b81f3ea32506f6/config/envs/default.py#L20
This makes copilot set the expected env vars. Note these are converted to screaming snake case env vars by Copilot
Have tested by deploying branch
=> BAU: match expected S3 bucket names

core/db/queries.py, core/serialisation/data_serialiser.py, tests/serialisation_tests/test_serialisation.py
https://dluhcdigital.atlassian.net/browse/SMD-90
Adds the columns LeadingFactorOfDelay and CurrentProjectDeliveryStage to the Project Progress tab.
- [X ] Unit tests and other appropriate tests added or updated
- [X ] README and other documentation has been updated / added (if needed)
- [X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
The new columns should be visible in the data extract under Project Progress, and the tests should pass successfully.
=> [smd-90] add delay and delivery stage fields to serialiser

core/extraction/towns_fund_round_one.py, core/extraction/towns_fund_round_two.py, core/extraction/utils.py
Add the same logic to drop the problematic cells as described in the readme here:
https://github.com/communitiesuk/funding-service-design-post-award-data-store/pull/233
Caveat:
Due to all the data being ingested from a single sheet, I think it is impractical to check if Programme only has been selected so that scenario has not bee include
=> [FMD-55] Remove bad FHSF data from historical ingest

core/extraction/towns_fund_round_four.py, core/extraction/towns_fund_round_three.py, core/validation/validate.py, tests/extraction_tests/resources/assertion_data/round_four/programme_progress_expected.csv, tests/extraction_tests/resources/assertion_data/round_four/project_progress_expected.csv, tests/extraction_tests/resources/assertion_data/round_four/risks_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/funding_comments_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/funding_data_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/funding_questions_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/outcomes_data_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/outcomes_ref_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/outputs_data_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/outputs_ref_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/place_details_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/programme_progress_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/project_details_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/project_progress_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/psi_expected.csv, tests/extraction_tests/resources/assertion_data/round_three/risks_expected.csv, tests/extraction_tests/test_round_four_extraction.py, tests/extraction_tests/test_round_three_extraction.py
Retains the original indexes of the DataFrames in df_ingest. Upon ingest, the indexes are decremented by two, and so when we relay the original_index information to validation messages it will have to be incremented by two. 
Points of note:
- Footfall outcomes are more difficult to retrieve specific row numbers for as their values span multiple rows in the original spreadsheet. They are therefore not accounted for in this PR.
- The original index is not retained for Project Details, but is instead added on after the transformation occurs. We know that Project 1 will always begin at line 27 of the spreadsheet, and that each project is incremented by 1, and can set the index accordingly.
=> [SMD-220]: retain original row indexes

core/const.py, core/validation/failures.py, core/validation/schema.py, core/validation/validate.py, tests/validation_tests/test_failures.py, tests/validation_tests/test_validate.py
validate_types() requires a refactor as it was working at the column-level and therefore incapable of bringing through row indexes. The function now works row by row within a given column, and can therefore return more responsive error messages.
This also includes retaining the index in validate_types() such that it can be passed onto WrongTypeFailure.
=> BAU: refactor validate types & retain index in WrongTypeFailure

core/extraction/towns_fund_round_four.py, core/extraction/towns_fund_round_three.py, tests/extraction_tests/test_round_four_extraction.py
https://dluhcdigital.atlassian.net/browse/SMD-238
- For Round 4 we need to collect an extra half of data where TF have un-greyed out the cells in the form for FHSF H1 24/25
The cells in red below used to be 
=> [SMD-238] ingest an extra half of funding data for round 4

core/extraction/towns_fund_round_four.py, core/extraction/towns_fund_round_three.py, core/util.py, core/validation/failures.py, core/validation/validate.py, tests/controller_tests/test_ingest.py, tests/extraction_tests/test_round_four_extraction.py, tests/extraction_tests/test_round_three_extraction.py, tests/validation_tests/test_failures.py, tests/validation_tests/test_validate.py
Relay the indexes of where an error has occurred to the validation failures for non R4-specific validation failures. Excludes WrongTypeFailure.
=> [SMD-236]: put indexes in validation messages for non-R4 specific errors

core/util.py, core/validation/failures.py, core/validation/specific_validations/towns_fund_round_four.py, tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py, tests/validation_tests/test_failures.py, tests/validation_tests/test_utils.py
This PR fixes a bug where the project number in the section field for some of the validation errors displayed does not match their on page position, for background this is because the projects in the sheet could be for example:
TD-ABC-01 - project 1
TD-ABC-03 - project 2
TD-ABC-05 - project 3
so we can't simple read the final part of the ID to get project number as we have done so far.
To fix this I have implemented two functions
- get_project_number_by_cell()
This uses the row index to get project number
- get_project_number_by_id()
this uses the project ID and the list of active ids
Then in the code wherever we need project number I have used which ever function is best for a given use case.
In the future we hope to refactor the to_message() and validatiion functions to only need one of …
=> [SMD-147] Fix project numbers in the wrong place in validation

core/util.py, core/validation/failures.py, core/validation/messages.py, core/validation/specific_validations/towns_fund_round_four.py, tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py, tests/validation_tests/test_failures.py
https://dluhcdigital.atlassian.net/browse/SMD-255
- moves the `construct_cell` function to `failures.py` as it's only used within the validation package
- implements the content changes to validation messages
- moves the messages out into formattable constants
- refactors the test module to avoid asserting on message contents as it's redundant and just adds to maintenance efforts
=> Smd 255 implement validation message content changes

core/validation/failures.py, tests/validation_tests/test_failures.py
Handles cases where footfall outcome validation errors return row_indexes = None
=> fix potential bug with footfall outcome cells

core/validation/specific_validations/towns_fund_round_four.py, tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py
Fix broken cell lookup for Leading Factor of Delay.
=> fix broken cell lookup for leading factor of delay

core/extraction/towns_fund_round_three.py, tests/extraction_tests/test_round_four_extraction.py, tests/extraction_tests/test_round_three_extraction.py
Fixes issue whereby cell rows are off by two for outcome project failures.
This was happening because we need to increment +2 in our DataFrames to match original Excel row. However, we currently do this incrementation post-transformation, but InvalidOutcomeProjectFailures are caught mid-transformation, hence lacking the increment.
=> fix cell off by 2 bug for outcome project failure

core/validation/validate.py, tests/validation_tests/test_validate.py
Fixes issue of composite keys returning multiple of the same cell. This was because of melting behaviour on the DataFrames.
=> fix duplicated cell bugs on composite keys

core/validation/initial_check.py, tests/validation_tests/test_pre_checks.py
Fixes bug whereby empty place_name returns a 500. .strip() is no longer required as no place_names in the sheet contain extraneous white spaces.
=> fix place names null bug

core/const.py, tests/validation_tests/test_failures.py
=> fix typo in cell mapping

copilot/environments/overrides/cfn.patches.yml
We need this to match the Cloudfront timeout to maximise the request time as otherwise loadbalancer will timeout requests after 60 seconds.
Have tested by running on pre-production environment
Have also run diff to check change e.g.
```
$ copilot env deploy --diff                         
Found only one environment, defaulting to: production
~ Metadata:
~ Version: v1.30.0 -> v1.30.1
~ Resources/PublicLoadBalancer/Properties:
+ LoadBalancerAttributes:
+     - Key: idle_timeout.timeout_seconds
+       Value: 180
```
=> FMD-105: override load balancer timeout

core/extraction/towns_fund_round_three.py, tests/extraction_tests/test_round_four_extraction.py, tests/extraction_tests/test_round_three_extraction.py
Fixes issue where putting a float into project progress rag ratings columns causes a 500.
=> [SMD-315]: float type in rag ratings bug fix

core/extraction/towns_fund_round_three.py, tests/extraction_tests/test_round_four_extraction.py, tests/extraction_tests/test_round_three_extraction.py
Fixes ints being cast to floats for RAG rating columns.
=> BAU: fix ints being cast to floats bug

core/controllers/ingest.py, openapi/components.yml, tests/controller_tests/test_ingest.py
- ingest now returns a metadata JSON object that can contain general information on a submission
- this allows us to add fund type ID to the response for Submit to use to further personalise emails to LAs and TF
=> [BAU] return fund type id in ingest response payload

core/validation/messages.py, core/validation/specific_validations/towns_fund_round_four.py, tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py
Prevents negative numbers in PSI.
Part of this bug ticket: https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?selectedIssue=SMD-314
=> [SMD-314]: prevent negative numbers in psi

core/const.py, core/validation/failures.py, core/validation/utils.py, core/validation/validate.py, tests/controller_tests/test_ingest.py, tests/test_misc.py, tests/validation_tests/test_failures.py, tests/validation_tests/test_validate.py
Implements functionality where by errors in the 'Amount' column for Outcomes are accurately mapped back to the original cell location in which that error has occurred.
=> [SMD-336]: accurate cell mappings for outcomes amount col

core/const.py, core/validation/const.py, core/validation/messages.py, core/validation/specific_validations/towns_fund_round_four.py, core/validation/utils.py, core/validation_schema.py, tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py, tests/validation_tests/test_utils.py
When a project is complete, "Currently Project Delivery Stage" and columns pertaining to upcoming comms milestones are now nullable.
=> [SMD-386]: make cols nullable depending on if project is complete

core/extraction/towns_fund_round_three.py, core/handlers.py, core/validation/failures.py, core/validation/failures/dev.py, core/validation/failures/user.py, core/validation/historical.py, core/validation/initial_check.py, core/validation/specific_validations/towns_fund_round_four.py, core/validation/validate.py, tests/controller_tests/test_ingest.py, tests/extraction_tests/test_round_four_extraction.py, tests/extraction_tests/test_round_three_extraction.py, tests/test_handlers.py, tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py, tests/validation_tests/test_failures.py, tests/validation_tests/test_pre_checks.py, tests/validation_tests/test_validate.py
- all `Failure`s are per cell for consistency 
- `Failure`s raised during historical ingest are separated from `failures.py` into `historical.py`
- moves common `Failure` attributes to a parent class to enforce consistency across `Failures`
Next refactor is to go further by modifying `validate.py` so separate historical validation from other validation - i.e. foreign key validation should never occur for non-historical rounds so we don't need to do that check. The plan is to make it configurable - i.e. you can configure a set of checks per dataset.
=> [BAU] validation failure refactor

core/extraction/towns_fund_round_three.py, tests/extraction_tests/resources/mock_sheet_data/round_three/place_identifiers_mock.csv, tests/extraction_tests/resources/mock_sheet_data/round_three/project_identifiers_mock.csv
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?selectedIssue=SMD-387
- use `strip` and `lower` when using lookups during extraction 
=> [SMD-387] during extract do lookups with stripped and lowered values

core/controllers/download.py, core/serialisation/data_serialiser.py, tests/controller_tests/test_download.py, tests/serialisation_tests/test_serialisation.py
Extract date fields (e.g. StartDate, EndDate on Funding) to be Excel dates not strings
=> [FMD-106] Write dates as Excel 'dates' not strings

core/validation/specific_validations/towns_fund_round_four.py, tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py
Fixes an issue found on the test environment where if a user entered non numerical funding data, the application would crash on trying to sum the funding data. Now we just skip the funding validation if this happens and rely on the type validation to flag the non-numerical data.
https://funding-service-design-team-dl.sentry.io/issues/4650934446/events/1ab5e3376f7541aa87504a05a4aab322/
=> [BAU] skip funding validation if data is non-numeric

core/handlers.py, core/validation/failures/user.py, openapi/api.yml, openapi/components.yml, tests/validation_tests/test_failures.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-427
Adds an extra list comprehension containing the Validation Exception types so they can be sent to the front end - they are not coupled with each exception themselves, but they can be if required.
=> SMD-361 return list of exception types for front end logging

core/const.py
=> removing trailing whitespace on ipswich la

core/const.py, core/controllers/ingest.py, core/controllers/mappings.py, core/extraction/towns_fund_round_one.py, core/util.py, core/validation/__init__.py, core/validation/casting.py, core/validation/failures/internal.py, core/validation/failures/user.py, core/validation/schema.py, core/validation/specific_validations/towns_fund_round_four.py, core/validation/validate.py, scripts/validate.py, tests/controller_tests/test_ingest.py, tests/controller_tests/test_mappings.py, tests/extraction_tests/test_round_four_extraction.py, tests/extraction_tests/test_round_three_extraction.py, tests/integration_tests/test_ingest_component.py, tests/test_handlers.py, tests/validation_tests/test_failures.py, tests/validation_tests/test_validate.py
https://dluhcdigital.atlassian.net/browse/SMD-403
Renames "spreadsheet" language to more generic language. The background to this is that when the validation was first developed, we built it expecting one table per sheet. This means that the use sheet/worksheet in place of "table" is very misleading now that we ingest data with multiple tables per sheet.
- renames all reference to workbook ---> data
- renames all reference to worksheet/sheet ---> table
=> [SMD-403] rename spreadsheet language

core/controllers/ingest.py, core/controllers/load_functions.py, core/controllers/load_functions_historical.py, core/db/queries.py, tests/controller_tests/test_ingest_functions.py, tests/db_tests/test_queries.py, tests/integration_tests/test_ingest_db_transactions.py
PR for refactoring ```populate_db()``` such that each table is loaded by a bespoke function rather than as part of a larger, more general function that distinguishes what table is being loaded with if statements.
Methods have also been pulled out of ```ingest.py``` and into ```load_functions.py``` where deemed appropriate.
=> [FMD-113]: refactor ingest logic

config/envs/development.py, config/envs/unit_test.py, tests/integration_tests/conftest.py, tests/integration_tests/test_aws.py
Move out the fixture to create and delete the unit test buckets for to conftest file so that they can be shared by all integration tests
=> BAU: fix fixture score for AWS integration tests

core/validation/__init__.py, core/validation/failures/internal.py, core/validation/messages.py, core/validation/pre_transformation_validation_schema.py, core/validation/specific_validations/towns_fund_round_four.py, core/validation/utils.py, core/validation/validate.py
Tidies docstrings inside the ```validation``` directory. 
Also removes a redundant piece of code that checked if a value was a list or not in ```validate_types```.
=> BAU: validation docstring tidy up

core/extraction/towns_fund_round_three.py, tests/extraction_tests/test_round_four_extraction.py, tests/extraction_tests/test_round_three_extraction.py
- fixes a bug found during re-ingest that caused returns with blank RAG cells to return enum validation errors due to `pd.NaN` being converted to `str` "nan"
=> [BAU] fix RAG type casting during transformation to retain pd.NA

core/controllers/ingest.py, core/extraction/towns_fund_round_three.py, core/validation/failures/user.py, core/validation/schema_validation/schemas.py, core/validation/specific_validation/towns_fund_round_four/validate.py, tests/extraction_tests/test_round_three_extraction.py
I have updated some of the ingest docstrings to reflect the current behaviour.
Removed __str__ methods from user failures. These failures are dataclasses so they already have __repr__ methods that will return very similar strings if called and these __str__ methods are no longer called in the application.
I have searched for TODO's and removed those that are no longer relevant and downgraded to comments those that don't state a specific action to be done.
=> BAU: General clean up of ingest user failures and unused TODO's

core/controllers/ingest.py, core/controllers/load_functions.py, tests/controller_tests/test_ingest_functions.py
In current code, we use the term "workbook" and "worksheet" post-transformation (transformation from the raw Excel workbook data into the data in the format of our data model, ready to be ingested into the database) to refer to the dictionary of transformed dataframes and the individual transformed dataframes respectively, which is misleading as "workbook" and "worksheet" are tied to Excel and Excel is not relevant post-transformation. This PR aims to resolve that.
=> BAU - Remove ambiguity around use of the term "workbook" for transformed data

core/controllers/retrieve_submission_file_db.py, tests/integration_tests/conftest.py, tests/integration_tests/test_aws.py, tests/integration_tests/test_ingest_component.py, tests/integration_tests/test_retrieve_submission_file.py
- Unify test_bucket setup to create & teardown all s3 buckets
- Move test_bucket fixture to conftest and remove duplicates from modules
- Update test_ingest_endpoint_s3_upload_failure_db_rollback test to make use of mocking to test behaviour with different raised exceptions
- Add default filename for submission files retrieved from database if no filename present in db
=> FMD-156: Add default filename for retrieved db submissions and update unit test s3 bucket setup

core/controllers/download.py, tests/controller_tests/test_download.py
Minor improvement to help programmers when configuring serialisation tables. If tables added via query/serialisation, it also needs to be specified in the sort-orders const.
=> BAU: improve serialisation programmer/config error

requirements-dev.in
Adding [pre-commit](https://[pre-commit](https://pre-commit.com/).com/) to the dev requirements to avoid the need to manually run `pip install pre-commit` after running `pip-sync requirements-dev.txt` after checking out a different branch in this repo.
=> Adding pre-commit to dev requirements

core/controllers/retrieve_submission_file.py, scripts/db_filename_clean.py, tests/integration_tests/test_retrieve_submission_file.py
- New script to cleanup `submission_filename` in Submission table and remove erroneous `%22` from start and end of filenames
- Add check against incorrect Round 4 filename of `ingest_spreadsheet` and replace with user-friendly and helpful filename on download
=> FMD-225: Add submission_filename cleanup script

.github/workflows/deploy.yml, Procfile, README.md, copilot/data-store/manifest.yml, project.toml, scripts/migration-task-script.py
Sister PR to: https://github.com/communitiesuk/funding-service-design-post-award-submit/pull/81
This changes the build process to produce a [Paketo](https://paketo.io/docs/howto/python/) image rather than using the local dockerfile, this means the underlying image is managed for us which improves security. 
This also includes the associated refactors to the DB migration script to use the Paketo image
Have tested on dev environment: https://github.com/communitiesuk/funding-service-design-post-award-data-store/actions/runs/7972571461
=> FMD-219: build and use paketo image instead of local dockerfile

core/db/queries.py, tests/serialisation_tests/test_serialisation.py
Fixes an issue whereby the query for OutputData was leading to a cartesian join.
=> BAU: fix output query

tables/process.py, tables/table.py, tables/tests/test_extract.py, tables/tests/test_validate.py, tests/integration_tests/test_ingest_component_pathfinders.py
[Fix cell reference string in case of ignored non-header rows](https://dluhcdigital.atlassian.net/browse/SMD-667)
By removing all index resetting during table processing, all table DataFrames contain the original indices from the spreadsheet, removing the need for additional logic to map back from table-scope row indices to original indices even in the case of arbitrary removal of rows. This allows us to dispense with the `first_row_idx` attribute of the `Table` class.
Because DataFrames now contain original indices and not reset ones...
- The `_remove_ignored_non_header_rows` method of `TableProcessor` had to be adjusted to remove rows based on `ignored_non_header_rows` indices matching the actual _position_ of rows in the DataFrame (the index values you'd get if you ran a …
=> SMD-667 - Fix cell reference string in case of ignored non-header rows

core/controllers/ingest.py, tests/integration_tests/test_ingest_component_pathfinders.py
[SMD-670 - Pathfinders - align extraction and validation config table names with spreadsheet for directed error messaging](https://dluhcdigital.atlassian.net/browse/SMD-670)
- Simply adding table name to error message. We use existing "section" field to align with TF / frontend
- Changes not in this PR include broader changes to extract config to support alignment with spreadsheet, which were subsumed into separate PR [SMD-666 - SMD-666 - Align table extraction with finalised spreadsheet](https://github.com/communitiesuk/funding-service-design-post-award-data-store/pull/492) for simplicity, as per comment on SMD-670 ticket
=> SMD-670 - Adding table name to error message for Pathfinders

core/table_configs/pathfinders/round_1.py, tables/checks.py, tables/tests/test_checks.py
[SMD-710 - Pathfinders - validate postcodes](https://dluhcdigital.atlassian.net/browse/SMD-710)
Add validation to check for postcode or comma-separated list of postcodes in postcodes field in "Project location" table from new Pathfinder Reporting Template.
=> SMD-710 - Pathfinders - validate postcodes

core/db/entities.py, core/db/queries.py, tests/conftest.py, tests/integration_tests/test_ingest_component_pathfinders.py
Fixes a bug wherein subsequent submission ids for PF were not incrementing correctly, and adds a test to ensure that subsequent submissions for the same round for different programmes for PF do not have any errors on load.
=> BAU: fix subsequent submissions for pf

core/db/queries.py, tests/conftest.py, tests/integration_tests/test_ingest_component_towns_fund.py
Fixes a bug wherein ```get_latest_submission_by_round_and_fund``` does a look-up based on ```fund_type_id```, which discerns TD and HS as different funds when they belong to the same round of submissions.
=> BAU: fix td and hs submission id bug

core/validation/specific_validation/towns_fund_round_four/validate.py, tests/validation_tests/specific_validation_tests/towns_fund_round_four_tests/test_tf_r4_specific_validations.py
make comms milestone and comms milestone date optional. We have existing ingested submissions which don't populate these fields and TF have confirmed they should be optional
Unit tests should pass, fields should be optional and not fail ingest if not populated.
=> SMD-731: make comms milestone and comms milestone date optional

core/controllers/mappings.py, core/serialisation/data_serialiser.py, db/migrations/versions/026_standardise_actual_forecast.py
Standardise actual/forecast column to always be 'state' in data_blob for both Funding and ProjectFinanceChange.
=> [FMD-256]: standardise actual forecast in db

core/const.py
Add Pathfinders mapping (to stop data-store throwing exception if Pathfinders sheet was ingested)
Should be able to render find frontend download page if Pathfinders sheet has been ingested
nges (if applicable)
=> FMD-264: add pathfinders to fund ID mapping

core/const.py, core/serialisation/data_serialiser.py, tests/serialisation_tests/test_serialisation.py
Changing name in data extract for this table due to request from Towns Fund (currently they are they are the only user of this tab). Request copied from teams channel TF Hotline, (Renata Walton, 12:45, 04/04/2024):
_"Hi 
Gideon_
_Goldberg
, without fully checking the contents as I'll need to pull this into out dashboard. Thank you all for finally getting this information in there. It's actually ProgrammeManagementFunding, as it's a specific type of payment which is made to LAs for PM activity. So can the name be changed?"_
=> update ProgrrammeManagementFunding tab name in serialised extract

core/db/entities.py, db/migrations/alembic.ini, db/migrations/versions/027_start_date_before_end.py, tests/conftest.py, tests/db_tests/test_constraints.py, tests/integration_tests/mock_tf_r3_transformed_data/Outcome_Data.csv, tests/resources/outcome_data.csv
Add constraints to our DB tables which have start/end dates, ensuring that end dates can't be before start dates.
Includes a couple of extra commits which tweak config so that:
* SQL is logged when migrations run, for information/records
* Migrations run in separate transactions (see 586359ca9d77cf746beadb309815035fd368573c for more info)
=> FMD-259: Add DB constraint to check date ranges

tables/checks.py, tables/tests/test_checks.py
Fixes two things:
1) When uploading a spreadsheet with null data and invalid postcodes in the postcode columns, only the null data is reported. (If each failure state is uploaded separately they are reported - but in combination only one is). Now both failures will be reported up front.
2) If entering invalid postcode data that is a non-string type (eg int, datetime), that would previously be accepted. Now it will be rejected correctly.
---
I would have liked to update an integration test spreadsheet to contain some int/datetime postcodes but I don't have excel, so ... what can you do 🤷  help please?
Edit the `tests/integration_tests/mock_pf_returns/PF_Round_1_Success.xlsx` file on the `Project location` tab. Change some of the postcode lists to be numeric eg `1234`, or date eg …
=> SMD-759: bug fix postcode validation

core/validation/specific_validation/pathfinders/round_1.py, tests/integration_tests/test_ingest_component_pathfinders.py, tests/validation_tests/specific_validation_tests/pathfinders/test_round_1.py
Adds cell_index for ```_check_actual_forecast_reporting_period``` errors.
=> BAU: cells for actual forecast error pfc

core/controllers/ingest.py, core/messaging/__init__.py, core/messaging/messaging.py, core/messaging/tf_messaging.py, core/validation/specific_validation/pathfinders/round_1.py, tests/integration_tests/test_ingest_component_towns_fund.py, tests/messaging_tests/test_messaging.py, tests/messaging_tests/test_tf_messaging.py, tests/validation_tests/specific_validation_tests/pathfinders/test_round_1.py
https://dluhcdigital.atlassian.net/browse/SMD-773
* Edit a valid spreadsheet and introduce multiple instances of a specific type of error across the same rows and/or columns.
* On `main` branch, upload the spreadsheet and confirm that the cell references as unordered.
* Checkout this branch, re-upload and confirm that the cell references are now ordered.
=> SMD-769 - Order error cell indexes logically

core/controllers/ingest_dependencies.py, core/messaging/__init__.py, core/validation/schema_validation/schema.py, core/validation/schema_validation/schemas.py, core/validation/schema_validation/validate.py, tests/validation_tests/schema_validation_tests/test_validate.py
- Add schema validation check to make sure project start dates are not later than project completion dates, for TF Rounds 3, 4 and 5
- Add new validation error message for invalid project dates
- Add unit tests for new validation function
- Amend a mock TF Round 3 or 4 spreadsheet from the repo and set project start dates to something later than the project completion date (or vice versa)
- Upload the spreadsheet to submit
- See that validation fails and errors are returned to the frontend
=> SMD-748: Validate TF project dates

app.py, core/controllers/ingest.py, core/metrics.py, requirements-dev.txt, requirements.in, requirements.txt, tests/integration_tests/conftest.py, tests/integration_tests/test_ingest_component_all_funds.py, tests/integration_tests/test_ingest_component_towns_fund.py, tests/integration_tests/test_ingest_metrics.py
https://dluhcdigital.atlassian.net/browse/SMD-776
Track some metrics around spreadsheet ingest success/failures so that we can get some indication as to the amount of pleasure/pain our users are having submitting funding progress reports. We'll be able to break down stats by organisation (LA), fund, reporting round, and validation error.
Unit tests pending, putting up as draft for early review.
* check the branch out locally
* configure data-store with its sentry DSN so that it can report metrics
* Upload some spreadsheets for a fund - try a mix of successes and different failures
* Look in Sentry under the 'Metrics' tab and choose some metrics+dimensions to graph.
=> SMD-776: Add some quick metrics via sentry

.pre-commit-config.yaml, app.py, core/controllers/ingest.py, core/controllers/load_functions.py, core/db/utils.py, core/messaging/tf_messaging.py, core/transformation/pathfinders/round_1/transform.py, core/transformation/towns_fund/round_3.py, core/validation/failures/__init__.py, core/validation/schema_validation/casting.py, core/validation/schema_validation/schema.py, core/validation/specific_validation/pathfinders/round_1.py, core/validation/specific_validation/towns_fund_round_four/validate.py, db/migrations/env.py, db/migrations/versions/025_rename_pg_management.py, pyproject.toml, requirements-dev.in, requirements-dev.txt, setup.cfg, tables/extract.py, tables/table.py, tables/validate.py, tests/controller_tests/test_ingest_functions.py, tests/db_tests/test_queries.py, tests/transformation_tests/towns_fund/test_round_3_transformation.py, tests/transformation_tests/towns_fund/test_round_4_transformation.py, tests/validation_tests/specific_validation_tests/pathfinders/test_round_1.py
https://dluhcdigital.atlassian.net/browse/SMD-812
Stop eagerly formatting log messages, which ends up causing some log messages to be double-formatted. When the initial format is injecting a dictionary into the string, the second format (by fsd_utils.logging) can error because the dict looks like a format injection point, but is incorrectly structured.
I've also switched black+flake8+isort out for [ruff](https://docs.astral.sh/ruff/), which is a fast modern tool that combines a bunch of formatting and linting rules. One of these will raise linting issues for log call that have eagerly-formatted log lines.
=> Stop logging with eagerly-formatted strings / move to `ruff`

tests/db_tests/test_queries.py
The DB test changed as per this PR was using the wrong fixture. This test was making uncommitted DB changes, but never rolled them back so they leaked into the integration tests, causing seemingly random errors that only happened when running tests in certain orders.
run full test suite locally
=> [BAU] Fix fixture scope misuse

core/controllers/ingest.py
No ticket - BAU change.
- Remove `load_data` method from `ingest.py` module and call `populate_db` directly from `ingest`
- Believe that `load_data` used to contain additional logic inc. possibility of calling `populate_db_with_historical_data`, but this was removed
=> BAU - Remove load_data from ingest.py module

config/envs/development.py
SQLAlchemy has a simple config option that enables logging of all queries send to the DB. By adding this to dev config we can make it easy (easier) to turn on in local.
=> Allow turning on SQL logging

core/table_configs/pathfinders/round_1.py, core/validation/specific_validation/pathfinders/round_1.py, tests/validation_tests/specific_validation_tests/pathfinders/test_round_1.py
[Validation on ingest for PF current underspend question](https://dluhcdigital.atlassian.net/browse/SMD-819)
- [A separate PR](https://github.com/communitiesuk/funding-service-design-post-award-data-store/pull/559) makes current underspend optional (nullable), allowing users to leave this field blank, which is fine as we are currently in Q4 (quarter 4)
- Outside of Q4 we want to validate that current underspend has been entered
- This requires cross-table validation as we need to check reporting period alongside current underspend
- This PR adds that cross-table validation check
=> SMD-819 - Pathfinders - current underspend cross-table validation

README.md, core/cli.py, core/controllers/get_filters.py, core/controllers/ingest.py, core/controllers/mappings.py, core/controllers/retrieve_submission_file.py, core/db/entities.py, core/db/queries.py, core/reference_data.py, core/serialisation/data_serialiser.py, db/migrations/versions/028_create_fund_ref_table.py, tests/conftest.py, tests/controller_tests/test_filters.py, tests/db_tests/test_constraints.py, tests/db_tests/test_entities.py, tests/db_tests/test_queries.py, tests/integration_tests/test_ingest_component_all_funds.py, tests/integration_tests/test_ingest_component_towns_fund.py, tests/integration_tests/test_ingest_db_transactions.py, tests/resources/fund_dim.csv, tests/resources/programme_dim.csv, tests/serialisation_tests/conftest.py, tests/serialisation_tests/test_serialisation.py
Adds a table, ```fund_dim```, which contains reference data relating to fund-specific metadata.
Changes ```fund_type_id``` in ```programme_dim``` to be an FK pointing to said table.
=> [FMD-265]: normalise fund reference data

tests/conftest.py, tests/resources/extracted_data.py, tests/validation_tests/specific_validation_tests/pathfinders/test_round_1.py
[Re-scope Pathfinders mock data fixture](https://dluhcdigital.atlassian.net/browse/SMD-823)
- **Refactor PF mock data creation into function for use in function-scoped fixture**
By moving all mock data creation into a function, we ensure that when this function is called from a Pytest function-scoped fixture, fresh mock data is created rather than the fixture simply recycling a reference to existing mock data.
- **Re-scoping PF mock data fixture from module to function**
Now that mock data is generated within a function that is called by the fixture, re-scoping the fixture from module to function level will work as intended and ensure that tests that use the fixture get a fresh set of mock data, minimising unintended side effects.
- **Removing mutation reversals to PF mock data fixture** …
=> SMD-823 - Re-scope PF mock data fixture

core/controllers/ingest_dependencies.py, core/controllers/load_functions.py, core/controllers/mappings.py, core/db/entities.py, db/migrations/versions/030_programme_junction_reporting.py, tests/integration_tests/test_ingest_component_pathfinders.py, tests/integration_tests/test_ingest_component_towns_fund.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FMD/boards/139?selectedIssue=FMD-260
Adds a new column `reporting_round` to the `programme_junction` table,
which will eventually replace the `submission.reporting_round` column.
This patch only starts populating the data and doesn't deal with
backfilling existing nulls. That will be done in a follow-up PR.
* Upload some spreadsheets
* Check the DB table `programme_junction` and see that the reporting round has been recorded.
=> Start tracking reporting round on programme junction

core/db/entities.py, db/migrations/versions/031_programme_junction_2.py, tests/conftest.py, tests/db_tests/test_queries.py, tests/integration_tests/test_ingest_db_transactions.py, tests/resources/programme_junction.csv, tests/serialisation_tests/conftest.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/FMD/boards/139?selectedIssue=FMD-260
Backfill the `programme_junction.reporting_round` column and make it non-nullable.
=> Backfill `reporting_round` and make non-nullable

core/controllers/ingest.py, core/controllers/load_functions.py, core/db/queries.py, tests/integration_tests/test_ingest_component_towns_fund.py, tests/integration_tests/test_ingest_db_transactions.py
Now that we have the `reporting_round` tracked on the
`programme_junction` table, lets switch all reads from
`submission.reporting_round` over to
`programme_junction.reporting_round`.
As well as changing DB reads, we also stop reading the `Submission_Ref`
dataframe that eventually populates the `submission` table. Instead, we
rely on the `reporting_round` variable passed into `ingest`, and we
cascade this through to `populate_db` so that it can avoid checking the
`Submission_Ref` data frame. This is because we'll shortly stop writing
`submission.reporting_round`, and remove it from the data frame, so
we're just preparing for that.
=> Stop reading `reporting_round` from submission table

core/controllers/ingest.py, core/controllers/ingest_dependencies.py, core/validation/pathfinders/cross_table_validation/ct_validate_r1.py, tests/validation_tests/pathfinders/cross_table_validation_tests/test_ct_validate_r1.py
[Pathfinders - replace hard-coded dependencies with dependency injection](https://dluhcdigital.atlassian.net/browse/SMD-653)
Currently we have an IngestDependencies class that is used by Pathfinders but only for initial validation schema and table to load function mapping, as the other dependencies don't map directly between Towns Fund and Pathfinders. For the dependencies that Towns Fund has but not Pathfinders, we specify None in the constructor for the IngestDependencies object when doing a Pathfinders run, while for the dependencies that Pathfinders has but not Towns Fund, we hard-code them in the main 'ingest' pipeline flow.
This change is to break apart IngestDependencies into three classes - a base IngestDependencies, containing shared dependencies; and then specific child classes …
=> SMD-653 - Dependency injection for Pathfinders

core/table_extraction/config/pf_r1_config.py, core/validation/pathfinders/schema_validation/columns.py
[Pathfinders - create commonly used pre-defined Column classes](https://dluhcdigital.atlassian.net/browse/SMD-640)
Following on from the refactoring work done for SMD-503 to tie Pathfinders validation check functions to error messages, this change ties column datatypes to check functions to further simplify the Pandera interface used in validation configuration, and in fact remove the Pandera library as a dependency completely from `pf_r1_config.py`. The benefit to building in checks to columns is that you guarantee type checking as part of validation and get more concise code, e.g., instead of having to type `pa.Column(float, checks.is_float())` you can type `float_column()`, allowing the developer to focus only on the non-datatype checks that form part of the business logic.
Originally …
=> SMD-640 - PF validation - tie column datatypes to checks

core/controllers/mappings.py, core/db/entities.py, core/transformation/pathfinders/pf_transform_r1.py, core/transformation/towns_fund/common.py, core/validation/towns_fund/schema_validation/schemas.py, db/migrations/versions/036_nullable_reporting_round.py, tests/conftest.py, tests/db_tests/test_constraints.py, tests/db_tests/test_queries.py, tests/integration_tests/mock_tf_r3_transformed_data/Submission_Ref.csv, tests/integration_tests/test_ingest_db_transactions.py, tests/serialisation_tests/conftest.py, tests/transformation_tests/pathfinders/test_pf_transform_r1.py, tests/transformation_tests/towns_fund/test_common.py
Now that we're storing this information on
`programme_junction.reporting_round`, and we're no longer reading from `submission.reporting_round`, we can start to phase out writes to that table.
=> Make submission.reporting_round nullable

db/migrations/.current-alembic-head, db/migrations/env.py
This will provide a clear conflict in git if there are PRs with overlapping migrations, ensuring that they are linearised before merge.
This will allow us to potentially disable the setting that forces PRs to be up-to-date before merging, which becomes a pain point with larger teams and repositories.
=> Write a lockfile for the head migration

core/db/entities.py, core/serialisation/data_serialiser.py, tests/controller_tests/test_filters.py, tests/integration_tests/test_ingest_component_pathfinders.py, tests/resources/submission_dim.csv
Removes the `submission.reporting_round` column from the code. The DB column itself will be dropped in a followup PR (https://github.com/communitiesuk/funding-service-design-post-award-data-store/pull/596) because migrations run before code deployment. If we drop the column, the code can still refer to the column when making queries (SQLAlchemy selects each column individually rather than using *). So any reads on the submission table may try to read from the `reporting_round` column, which the migration will remove. That would raise errors.
Also updates a few unit tests and fixtures to remove `reporting_round` entries that were missed previously.
=> Remove submission.reporting_round

copilot/data-store/addons/data-store-cluster.yml
Update copilot manifest to point to new `bastionSecurityGroup` secret in AWS.
This moves the secret to an environment level and decouples from the other data-store secrets, avoiding a cyclical reference to the key in the manifest before it's been created if re-creating the application from scratch.
=> BAU: Update Bastion Security Group config

copilot/data-store/manifest.yml
Enable rolling deployments on pre-prod environments (The downtime was causing a sentry alert)
Should not cause a sentry alert following deployment
=> BAU: Enable rolling deployments on pre-prod environments

.github/workflows/deploy.yml
The celery deploy is stuck at 'review in progress'. I think data-store actually needs to go first (at least for the first run), so that it can update data-store addons and export values for the data-store-celery workload to use.
=> Switch copilot deployment order

copilot/data-store/addons/data-store-redis.yml
When deploying this infrastructure change to production, AWS CloudFormation was unable to create the cluster because the replication group ID ('funding-service-data-store-redis-production') was too long; there is a hard limit of 40 characters on the replication group name. Which we didn't know/factor in beforehand. This deployed find on dev and test environments because those envs have shorter names (...dev and test), which coincidentally stayed under the limit.
I've manually applied these changes to dev and test environments already to get everything consistent there, which involved:
* deleting the data-store-celery services, as they rely on the existing (badly-named) redis rep. group.
* renaming all of the resources in the redis coplit manifest with a '2' suffix to make them unique
* …
=> Use a shorter redis group name

requirements-dev.txt, requirements.in, requirements.txt
Pull in latest fsd_utils, so that we can use the latest version of sentry, which has queue monitoring features.
=> Bump fsd-utils/sentry SDK for queue monitoring

app.py, core/celery.py, requirements-dev.txt, requirements.txt
https://dluhcdigital.atlassian.net/browse/FPASF-104
Updates fsd_utils to pull in the [new utils changes](https://github.com/communitiesuk/funding-service-design-utils/pull/148) that change how logging is configured behind-the-scenes (to use dictConfig rather than imperatively configuring the loggers).
This means that we can grab the default logging config and use that to configure the celery workers, too, giving us consistent logging via the Flask app logger.
=> Celery logging

core/controllers/async_download.py, tests/integration_tests/test_async_download.py
Force presigned URLs for find download files to actually download, as otherwise the browser may choose to open them in the browser (eg in web excel).
=> Force file to download rather than open in the browser

core/controllers/async_download.py, core/db/queries.py, tests/db_tests/test_queries.py
When using the swagger UI to hit `trigger_async_download`, if the `send empty values` checkbox is filled, then the API request sent for the `organisation` (for example) field will be: `['']`.
This is treated as 'truthy' for the query, so would end up running some SQL like `WHERE organisation_id = ''::uuid`.
SQL can't convert an empty string to a UUID, and so throws an error.
Let's fix this by filtering out any empty string values first.
=> Prevent downloads from failing on empty strings

app.py, tests/common_tests/test_maintenance_mode.py
https://dluhcdigital.atlassian.net/browse/FPASF-451
Allows hitting `/healthcheck` in maintenance mode
=> Allow healthcheck in maintenance mode

README.md
Update the README to point at docker-runner immediately, as that's now the recommended/"officially supported" way to run the service(s).
=> Point to docker-runner at the top; fix some markdown linting issues

.github/workflows/deploy_combined_service.yml
Updates the GitHub deployment workflow to run copilot deploys of `celery` & `post-award` services and the `download-report` job in parallel. 
See example deployment run: https://github.com/communitiesuk/funding-service-design-post-award-data-store/actions/runs/10176167218
=> FPASF-460: Parallelise copilot deployments

pytest.ini, requirements-dev.txt, requirements.in, requirements.txt, tests/data_store_tests/transformation_tests/test_transformation_utils.py, tests/find_tests/test_routes.py, tests/submit_tests/test_routes.py
Turn warnings into errors so that we always deal with them
At the moment, warnings emitted during the test run are reported at the
end. But we've basically just been ignoring these and not doing anything
about them.
We can instead tell pytest to report them as errors, which will result
in failed test runs. This will force us to deal with warnings emitted by
our (or our dependencies') code. These can be things like
DeprecationWarnings, which can be early warning signs for our
dependencies changing how things are done and that we need to make
changes in our code.
Or they can be telling us that we're using some library incorrectly or
imprecisely, and should probably do something different.
To make sure that we're staying on top of our code, we should have a
rule that all warnings are …
=> Fix deprecation warnings and turn them into errors in the future

data_store/controllers/load_functions.py, data_store/exceptions.py, tests/integration_tests/test_ingest_db_transactions.py
`add_project_geospatial_relationship` is in our `data_store` module, which should need no concept of HTTP requests. This function, however, uses flask's `abort` call in situations where an error has happened. Instead, we should just raise an exception, which will bubble up to the relevant view and then be handled by flask as a 500. (Or it could be caught and handled appropriately)
https://dluhcdigital.atlassian.net/browse/FPASF-288
=> Add exception for missing postcode data

find/scripts/extract_download_logs.py
The environment names for prod(uction) after different between pre-award and post-award. This was missed in the monolith migration.
=> Translate prod->production for download report

copilot/download-report/manifest.yml, find/scripts/extract_download_logs.py
All of the logs from pre-monolith times have now been scraped and sent to our performance analyst, so we no longer need to (try to) touch this log group. Goodbye.
(Also, when the job ran in the context of the `pre-award` cluster it couldn't even read from a service's log group in the `post-award` cluster. But fortunately we still had the scheduled job running in the old world, so the report was still pulled down successfully there).
--
Also updates the sentry DSN for the download report to go into the "data-store" project.
=> Remove post-award log group from find download report

copilot/download-report/manifest.yml
The env name in the manifest is wrong, so `NOTIFY_SEND_EMAIL` isn't being injected correctly
=> Fix env name for download report

README.md, config/envs/unit_test.py, pytest.ini, requirements-dev.in, requirements-dev.txt, requirements.in, requirements.txt, tests/conftest.py, tests/e2e_tests/helpers.py, tests/e2e_tests/pages/__init__.py, tests/e2e_tests/pages/find.py, tests/e2e_tests/test_find.py, tests/integration_tests/test_async_download.py
Adds a browser test using Playwright that walks through the main user journey for a find user.
This involves:
* selecting some filters
* select a download file format
* clicking download
* clicking the link in the email that is received later
* downloading the final report on the page
We need to do some incredibly funky stuff around authentication to get a valid user session (in a way that could feasibly work against dev and test environments, too). We (ab)use authenticator's magic links flow to create a link as if we're an assessor of a new "post-award-e2e-tests" fund (which we inject into the local mock data for authenticator in a PR on that repo). When we use the magic link, it sets a cookie on the .levellingup.gov.localhost that is valid for Find, so we become effectively logged in. …
=> Initial playwright setup - test find flow

requirements-dev.in, requirements-dev.txt
Fixes an issue with `pip sync`:
```
sam:~/work/dluhc/funding/funding-service-design-post-award-data-store [bump-pip-tools]$ pip-sync requirements-dev.txt
Traceback (most recent call last):
File "/Users/sam/work/dluhc/funding/funding-service-design-post-award-data-store/venv/bin/pip-sync", line 5, in <module>
from piptools.scripts.sync import cli
File "/Users/sam/work/dluhc/funding/funding-service-design-post-award-data-store/venv/lib/python3.11/site-packages/piptools/scripts/sync.py", line 16, in <module>
from .. import sync
File "/Users/sam/work/dluhc/funding/funding-service-design-post-award-data-store/venv/lib/python3.11/site-packages/piptools/sync.py", line 11, in <module>
from pip._internal.commands.freeze import DEV_PKGS
ImportError: cannot import name 'DEV_PKGS' from …
```
=> Upgrade pip-tools

.github/workflows/aws_copilot_deployment.yml, .github/workflows/deploy_combined_service.yml, .github/workflows/deployment_cd_test_prod.yml
Implements a single pipeline that builds, tags (using the commit SHA rather than the branch name or `latest`), pushes and deploys to the `test` environment when PRs are merged into `main` and then just deploys the same image to production (`prod`) after approval. 
Also updates the old manual branch deployment workflow to make use of the new reusable workflow for consistency and also (for now) removes the ability to deploy to prod from this workflow to avoid clashes.
Testing still needed on how this all works in practice, which we can't do until this gets merged in and we can observe the behaviour 😬, but testing of the reusable workflow has been done with the manual deploy to `dev`.
=> FPASF-461: Update deployment workflows

project.toml
We had a gnarly problem recently (well, it's been around for a while now) that has made manual use of `flask` CLI commands on deployed environments have the wrong AWS credentials.
When our code is running in AWS, the container gets all of its permissions from its IAM task role. These are collected automatically by boto3 by talking to an ECS metadata endpoint on the container. However, boto3 will first look in the environment for any access keys. We don't provide credentials by environment variable, so normally this is fine.
However, when you specifically use the `flask` command, it will read a `.flaskenv` file and fill in any missing environment variables from that file. In this file we set AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_ENDPOINT_OVERRIDE. As these aren't in the …
=> Exclude some files from built container images

copilot/post-award-celery/manifest.yml, copilot/post-award/manifest.yml
remove -2 aliases from pre-prod envs
URLs without `-2` should resolve post-deployment.
=> FPASF-397: remove -2 aliases from pre-prod envs

.github/workflows/deploy_combined_service.yml
Limit branch deployments to dev. (We want to keep test running `main`.)
Post merge action should only be able to deploy to dev
=> BAU: Limit branch deployments to dev

scripts/migration-task-script.py
The idea is:
- run `flask db current` to get current revision id
- check `.current-alembic-head`
- if they match don't run migration
Deploy `test` it should reduce the migration step from 2.5mins to about 10 seconds
Job without new migration: https://github.com/communitiesuk/funding-service-design-post-award-data-store/actions/runs/10491220510/job/29059940501
Job with new migration: https://github.com/communitiesuk/funding-service-design-post-award-data-store/actions/runs/10491335472/job/29060378690
=> Add checks if migrations are needed

.github/workflows/aws_copilot_deployment.yml, .github/workflows/deploy_combined_service.yml, .github/workflows/deployment_cd_test_prod.yml
Our current deployment pipeline runs three jobs in parallel:
1. Migrate DB and deploy post-award service
2. Deploy post-award-celery service
3. Deploy download-report job
If the DB migration fails, we still deploy post-award-celery and the
download-report job. These might be relying on model changes from a DB
migration, so it is logically incorrect to be deploying these if the
migration fails. It also leaves us in an inconsistent place - post-award
service is on the old code, post-award-celery/download-report are on the
new code.
We should run the DB migrations before deploying any of the code
changes. If these succeed, we can run all three deployments. If they
fail, we shouldn't run any.
=> Migrate DB before code deployments

.pre-commit-config.yaml, data_store/aws.py, requirements-dev.in, requirements-dev.txt, tests/conftest.py
We weren't installing many of the actual type hints for boto3, leading to some AWS types falling back to `Any` (ie no type checking). This pulls in the essential packages and then fixes some of the code that is incorrect.
=> Fix type hints for boto3

README.md, config/envs/unit_test.py, pytest.ini, tests/conftest.py, tests/e2e_tests/conftest.py, tests/e2e_tests/helpers.py, tests/e2e_tests/pages/__init__.py, tests/e2e_tests/pages/find.py, tests/e2e_tests/test_find.py
https://dluhcdigital.atlassian.net/browse/FPASF-471
This adds the '--e2e-env' option to our e2e tests so that they can target the deployed dev and test environments.
By default these will still just run against the local domains, but this is a step towards us being able to run these tests in CI.
For now, the find test remains broken in dev+test envs because we are hardcoding our filter choices, and these are not reliably present in each environment. This will be fixed later, but getting this in now should unblock another developer's work on playwright tests.
- `pytest --e2e --headed --slowmo 1000  --e2e-env dev`
=> Allow e2e tests to target dev+test environments

pyproject.toml
This is a replacement for `strict-concat` (and possibly some others); "Warning: --strict-concatenate is deprecated; use --extra-checks instead"
=> Enable mypy "extra checks"

.pre-commit-config.yaml, data_store/controllers/notify.py, data_store/db/entities.py, data_store/db/queries.py, requirements-dev.in, requirements-dev.txt
These are only required for sqlalchemy<2, and with sqlalchemy>=2 they infact become misleading/incorrect.
This does mean that we need to install sqlalchemy itself (and specifically the same version we use in our real code) in the pre-commit hook.
=> Remove sqlalchemy-stubs

find/main/routes.py, find/scripts/extract_download_logs.py, tests/find_tests/test_logging.py
Ticket:
https://dluhcdigital.atlassian.net/browse/FPASF-537
Description:
The users' email addresses should not be logged for download, to avoid logging of PIIs.
To have the email addresses included in the file generated by the report script, a call for each user_id is done to account-store to get that.
Unit test updated, to check that email_address is no longer logged.
=> Logging for download

find/main/routes.py, tests/find_tests/test_routes.py
A recent change tweaking the names of some variables caused this value to stop being shown on the page.
https://github.com/communitiesuk/funding-service-design-post-award-data-store/commit/85c5ecacbb4152fbc0dd32e8a2afc87909281deb#diff-ee51d81c6e3fc5850fa1c22b90d04b8a1262d02a3b76ffd93e417b56008f3222R168
This unwinds the variable renaming and adds a test to prevent regression.
=> Show find report date on download page

app.py, common/templates/common/base.html, find/templates/find/base.html, find/templates/find/main/login.html, submit/templates/submit/base.html
https://dluhcdigital.atlassian.net/browse/FPASF-433
Previously, we allowed custom JS to execute in the browser by whitelisting the hashes of the script contents. This had a few issues
* We reference some JS by domain names, so needed to have the hash for each of our environments whitelisted.
* We didn't comment these well, so it's unclear which hashes are whitelisting which scripts.
We now stop using the hash whitelist and move over to CSP nonces. These are random values that we associate with each custom inline script to tell the browser they're trusted and can be executed.
The CSP nonce present on each script tag must match the CSP nonce passed back in the HTTP response header, otherwise the browser will refuse to run the script.
- Run the tests. Maybe even the nice new end-to-end tests …
=> Move from script hashes to CSP nonces

requirements-dev.txt, tests/e2e_tests/config.py, tests/e2e_tests/conftest.py
This closes the browser contexts correctly at the end of each test run,
and uses playwright's `new_context` fixture which will pass default
parameters correctly, therefore allowing flags like `--video=on` to work
properly.
=> Include default context args and close gracefully, and bump playwright version

build.py, common/templates/common/base.html, find/templates/find/base.html, find/templates/find/main/help.html, find/templates/find/main/login.html, requirements.in, submit/templates/submit/base.html, tests/common_tests/test_maintenance_mode.py
https://dluhcdigital.atlassian.net/browse/FPASF-571
Upgrades us from GOV.UK Frontend v5.40 to v5.6.0. And tweaks the `build.py` script so that it can be run even if you have old assets in `./static/src` - it will just delete and overwrite them. To simplify the upgrade path for local use.
* Build the container locally
* Check that everything still looks the same and works.
* Maybe run the new `e2e` tests ;)
=> Upgrade to GOV.UK Frontend v5.6.0

data_store/controllers/ingest.py, data_store/controllers/ingest_dependencies.py, data_store/table_extraction/config/pf_r1_config.py, data_store/table_extraction/extract.py, data_store/transformation/pathfinders/pf_transform_r1.py, data_store/transformation/towns_fund/tf_transform_r3.py, data_store/transformation/towns_fund/tf_transform_r4.py, data_store/validation/__init__.py, data_store/validation/initial_validation/checks.py, data_store/validation/initial_validation/initial_validate.py, data_store/validation/pathfinders/cross_table_validation/ct_validate_r1.py, data_store/validation/towns_fund/fund_specific_validation/fs_validate_r4.py, data_store/validation/towns_fund/schema_validation/casting.py, data_store/validation/towns_fund/schema_validation/validate.py, scripts/validate.py
On the current version of `pandas` `read_excel` returns a
`dict[int | str, pd.DataFrame]`.
We incorrectly typed it `dict[str, pd.DataFrame]`. Everywhere.
Luckily the new version of `pandas` returns our version of type-hint.
Until we upgrade pandas version, we should force Python to see it as
`dict[str, pd.DataFrame]`. After upgrade we can remove the `typing.cast`.
=> Adjust pandas read excel type hint

.github/workflows/test.yml, .pre-commit-config.yaml
We are starting to but up against problems using precommit.ci because they "only" allocate ~250mb storage for python dependencies, and we are starting to need to install more than that to allow `mypy` to run with all of the code context it needs.
So this PR moves the `mypy` type check into github actions, but leaves everything else running in precommit.ci since some of the devs like how that works.
=> Run type checks in github actions

.github/workflows/test.yml, .pre-commit-config.yaml
Now that we're running mypy in github actions, where python is installed and already has all of our dev dependencies available, we can use a system hook instead of the mypy repo hook.
This will make pre-commit run the `mypy` that is available in the current environment, which will be the one pinned by our requirements-dev.txt. Because it uses that mypy, and the environment's python interpreter, all of our dev dependencies will also inherently be available for mypy's type checking, which should give us the best checks available.
=> Use a system hook for pre-commit mypy

tests/conftest.py, tests/data_store_tests/controller_tests/test_filters.py, tests/data_store_tests/db_tests/test_constraints.py, tests/data_store_tests/db_tests/test_queries.py, tests/data_store_tests/serialisation_tests/conftest.py, tests/integration_tests/test_ingest_component_pathfinders.py, tests/integration_tests/test_ingest_db_transactions.py
In some previous code, we created the ReportingRound model and instances to replace a bunch of disparate data spread across various models.
We didn't update all of the tests to consistently have ReportingRound entities attached via relationships, so this patch fixes it.
=> Update test fixtures for ReportingRound model

data_store/cli.py
https://dluhcdigital.atlassian.net/browse/FPASF-493
We're migrating from having some reporting round info on the Submission and ProgrammeJunction tables to a separate ReportingRound entity.
This small CLI command will give us confidence that we can drop the old columns because the data is matched up correctly.
* Run `flask validate reporting-round-data` on your local machine and check the output.
* If nothing is broken, Invalidate some Submissions/ProgrammeJunctions in your local DB and re-run.
=> Add a CLI command to validate reporting round data

data_store/db/entities.py, db/migrations/.current-alembic-head, db/migrations/versions/041_new_programme_round_constrai.py
https://dluhcdigital.atlassian.net/browse/FPASF-493
Because we'll be removing the other unique constraint that currently looks at programme_id + reporting_round (number).
=> New unique constraint for programme junction

data_store/controllers/admin_tasks.py, data_store/controllers/get_filters.py, data_store/controllers/load_functions.py, data_store/controllers/retrieve_submission_file.py, data_store/db/queries.py, data_store/serialisation/data_serialiser.py, tests/conftest.py, tests/data_store_tests/controller_tests/test_filters.py, tests/data_store_tests/db_tests/test_queries.py, tests/data_store_tests/serialisation_tests/test_serialisation.py, tests/integration_tests/test_retrieve_submission_file.py
https://dluhcdigital.atlassian.net/browse/FPASF-493
This patch stops using both the Submission.reporting_period_[start|end] and ProgrammeJunction.reporting_round fields, instead preferring to reach into the ReportingRound table/entity itself for that data.
* Checkout the main branch
* Restart docker-compose so that celery is running `main` code
* Upload a submission
* Do a JSON data dump from Find (maybe use filters to restrict to only dump that submission)
* Switch over to this branch. Remember that celery doesn't hot reload, so you may need to docker-compose down and up again.
* Re-ingest the same submission.
* Do another JSON dump from Find with the same filters. The JSON files should match exactly (except for maybe `SubmissionRef.ReportingPeriodEnd` where we have some potentially …
=> Start using ReportingRound directly

data_store/table_extraction/config/pf_r1_config.py, data_store/validation/pathfinders/consts.py, data_store/validation/pathfinders/cross_table_validation/ct_validate_r1.py, data_store/validation/pathfinders/r1_consts.py, data_store/validation/pathfinders/schema_validation/checks.py
[Pathfinders - Proposed Amendments requested June '24](https://dluhcdigital.atlassian.net/browse/FPASF-453)
A precursor to the actual changes to support Pathfinders round 2 ingest. This PR is for separating validation constants that are shared versus those likely to be round-specific.
This is refactoring rather than new functionality; all existing tests passing should suffice.
=> RFP-453 - Precursor - Separating shared and round-specific validation constants

data_store/reference_data.py
https://dluhcdigital.atlassian.net/browse/FPASF-494
We are removing the old reporting round columns on these tables, so they won't be available for backfilling lookups any more. All of our deployed and local data has already been migrated, so this is no longer required.
=> Stop backfilling ProgrammeJunction/SubmissionDim for reporting rounds

admin/__init__.py, admin/actions.py, admin/base.py, admin/entities.py, admin/forms.py, admin/templates/admin/reingest.html, admin/templates/admin/retrieve_failed_submission.html, admin/templates/admin/retrieve_submission.html, app.py, config/envs/default.py, config/envs/development.py, data_store/db/entities.py, pyproject.toml, pytest.ini, requirements-dev.txt, requirements.in, requirements.txt, tests/admin_tests/test_auth.py, tests/conftest.py, tests/find_tests/test_routes.py, tests/submit_tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/FPASF-579
Integrates [Flask-Admin](https://flask-admin.readthedocs.io/en/v2.0.0a0/) with some basic admin views:
* View funds
* View geospatial dim (postcodes)
* View organisations
* View outcomes
* View outputs
* View submissions
* View and create reporting rounds
* Re-ingest submission by ID
* Download submission spreadsheet by ID
* Retrieve failed (500-style error) submission by UUID
These are all protected by membership of the `FSD_ADMIN` Microsoft AD group.
* Go to http://find-monitoring-data.levellingup.gov.localhost:4001/admin/
=> Add basic flask-admin views

data_store/db/entities.py, tests/data_store_tests/db_tests/test_constraints.py
https://dluhcdigital.atlassian.net/browse/FPASF-494
Removes the old reporting round columns from python model defintions. Once this is out, we know that no code is using those columns, and we can remove them safely in a future migration PR.
**Note**: I know that the DB migrations check will fail, because there are outstanding migrations. But this is intentional.
=> Remove definitions of old reporting round columns

.github/workflows/aws_copilot_deployment.yml, .github/workflows/deploy_combined_service.yml
I find myself fairly often doing deploys of branches to dev and then manually triggering the e2e test suite. I think it's fine to just put these two together by default.
=> Run e2e tests by default when deploying; allow dev

pyproject.toml
The `check_untyped_defs` setting in mypy instructs mypy to type-check functions that don't have type annotations. By default, mypy skips checking the internal logic of functions that don't explicitly declare types (i.e., untyped function definitions). Enabling check_untyped_defs forces mypy to analyze these untyped functions as if they had implicit Any types.
In summary:
Enabled (True): mypy checks all functions, even those without type annotations.
Disabled (False): mypy skips type checking for functions without type annotations.
`mypy` should pass
`pytest` should pass
=> FPASF-559: Enable check_untyped_defs rule

data_store/transformation/pathfinders/pf_transform_r2.py, tests/data_store_tests/transformation_tests/pathfinders/test_pf_transform_r2.py
As part of the changes for Pathfinders Round 2, we've updated the headers for some of the tables to include "everything so far up to march 2024". The start date for these was previously unclear but Pathfinders team have recently clarified that it should be considered 2019-01-01, so let's update.
=> Update start date for pathfinders r2

requirements-dev.in, requirements-dev.txt
Add `watchdog` dependency to celery auto refresh.
- Pull this branch
- Pull docker-runner branch from [this PR](https://github.com/communitiesuk/funding-service-design-post-award-docker-runner/pull/50)
- Run docker runner
- Download a find report
- Make a change to any .py file in the project (I added a print in the download async function)
- You will not see docker-runner say that celery was restarted
- OR if you added a `print` you will not see it printed on download
- Stop docker runner
- Set inside the docker runner CELERY_AUTO_REFRESH to `true`
- Start docker runner
- Make a change to any .py file in the project (I added a print in the download async function)
- You will not see docker-runner say that celery was restarted
- OR if you added a `print` you will not see it printed on …
=> Add watchdog for celery auto refresh

copilot/post-award/manifest.yml
[Deploy code live and enable Round 2 reporting from given start date](https://dluhcdigital.atlassian.net/browse/FPASF-580)
Using AWS Parameter Store to configure `ENABLE_PF_R2` on all AWS envs (dev, test and prod) ready for PF R2.
=> Use Parameter Store variable to allow activation of PF R2 on all environments

data_store/const.py, data_store/controllers/ingest.py, data_store/db/queries.py, data_store/transformation/pathfinders/pf_transform_r1.py, data_store/transformation/pathfinders/pf_transform_r2.py, data_store/transformation/towns_fund/common.py, data_store/transformation/towns_fund/tf_transform_r3.py, data_store/transformation/towns_fund/tf_transform_r4.py
https://dluhcdigital.atlassian.net/browse/FPASF-495
Stop using the hard-coded dictionaries that contain reporting round
dates. Instead, we can now just reference the reporting round records
in the DB directly.
This change means that ingesting a spreadsheet will no longer *create* a
new ReportingRound entry - this is now a thing that needs to be done
manually by a developer as part of setting up a new reporting round for
a fund. It's very low maintenance, however, using the flask-admin
interface.
=> Use ReportingRound as reference data

app.py, config/envs/development.py, tests/e2e_tests/pages/find.py, tests/e2e_tests/pages/submit.py
When flask-debugtoolbar is enabled locally, it injects a lot of HTML onto the page to
help explain what's happened when processing the request. This has
subtly broken our e2e tests (but only when running locally with
flask-debugtoolbar enabled).
The easy part of the fix is to tweak our selectors for key elements
during the find and submit tests. When selecting a radio button for file
type, specifically select the input label. When clicking a link for
Pathfinders, specifically look for a link.
We also turn off flask-debugtoolbar redirect interception by default, so that e2e tests
don't have to deal with that.
---
Finally, the e2e tests flagged some more CSP hashes we "need" to add for a couple of obscure flask-debugtoolbar inline styles 🙃
=> Fix e2e tests when running locally

data_store/controllers/ingest.py, data_store/controllers/ingest_dependencies.py, data_store/messaging/tf_messaging.py, data_store/validation/__init__.py, data_store/validation/towns_fund/fund_specific_validation/fs_validate_r4.py, data_store/validation/towns_fund/fund_specific_validation/fs_validate_r6.py, tests/data_store_tests/validation_tests/towns_fund/fund_specific_validation_tests/test_fs_validate_r4.py, tests/data_store_tests/validation_tests/towns_fund/fund_specific_validation_tests/test_fs_validate_r6.py
[Update TF validation for next reporting round](https://dluhcdigital.atlassian.net/browse/FPASF-185)
[Make necessary coding changes](https://dluhcdigital.atlassian.net/browse/FPASF-583)
Added a new validation rule for the Projects Progress Summary table. It checks that projects marked as "Not yet started" don't have a Start Date in the past. If violated, it triggers a `DATA_MISMATCH_PROJECT_START` error with the content "A Project has not yet started but has a Start Date prior to today declared."
- Create a copy of the TF R5 spreadsheet (`funding-service-design-post-award-data-store/tests/integration_tests/mock_tf_returns/TF_Round_5_Success.xlsx`)
- In the copy, change cell G21 on tab "3 - Programme Progress" to "Not yet started"
- In …
=> FPASF-583 - Support new 'Project progress' validation requirement for TF R6

data_store/controllers/mappings.py, tests/data_store_tests/controller_tests/test_mappings.py
No ticket created - happy to create one.
Database load has always been a bit of a pain point in our code. So rather than just talk of a big future refactor, I thought I'd begin with an incremental improvement to readability that I spotted as an opportunity a while back. Basically, in the mappings module at the moment, we have a namedtuple `FKMapping` defined but then not used at all (except in tests), and then we have unlabelled tuples used throughout the rest of the module for the `fk_relations` attribute of `DataMapping` instances. This PR replaces the namedtuple with a dataclass and then actually uses this throughout the module, improving readability by making it obvious what each element represents in each `DataMapping`'s `fk_relations` list.
=> Create and use FKMapping class in mappings.py module

scripts/pf_r2_outputs_outcomes_fix.sql
[Fix PF R2 outputs / outcomes validation issue](https://dluhcdigital.atlassian.net/browse/FPASF-599)
This PR contains an SQL script that is to be run against the production database, to update the names of the outputs that were renamed between Pathfinders rounds 1 and 2. By running these updates, in conjunction with the code in the other PR for this ticket (see ticket comments), we ensure that the same real-world output maps to a single output in the database, despite the name change.
=> FPASF-599 - PF R2 - SQL to change output names to account for text changes between round 1 and round 2 of Pathfinders reporting

data_store/transformation/pathfinders/pf_transform_r1.py, data_store/validation/pathfinders/cross_table_validation/common.py, data_store/validation/pathfinders/cross_table_validation/ct_validate_r2.py, tests/data_store_tests/transformation_tests/pathfinders/test_pf_transform_r1.py, tests/data_store_tests/validation_tests/pathfinders/cross_table_validation_tests/test_ct_validate_r2.py
[Fix PF R2 outputs / outcomes validation issue](https://dluhcdigital.atlassian.net/browse/FPASF-599)
A copy and paste of outputs and outcomes from an unverified location into the R2 spreadsheet that was sent out to LAs broke the link between the outputs and outcomes control tables in the hidden worksheets and the outputs and outcomes user tables in the user-facing worksheets. An analysis identified several small discrepancies between the outputs and outcomes as they appear in round 1 and the outputs and outcomes as they appear in round 2, specifically differences in whitespace, capitalisation and in one case, a spelling fix ('Ratinalised').
Because we are going to apply the spelling fix manually to production data, we need to apply the spelling fix as a transform in the PF round 1 ingest …
=> FPASF-599 - PF R2 - accounting for textual discrepancies in outputs and outcomes between rounds 1 and 2

data_store/db/queries.py, data_store/serialisation/data_serialiser.py, tests/conftest.py, tests/data_store_tests/serialisation_tests/test_serialisation.py, tests/integration_tests/test_ingest_component_all_funds.py
Ticket:
https://dluhcdigital.atlassian.net/browse/FPASF-588
Description:
This is the first step of the work in the ticket, to add "SubmissionDate" to the "SubmissionRef" section of the data extract.
Screenshot:
=> Add SubmissionDate to download's SubmissionRef section

data_store/validation/towns_fund/fund_specific_validation/fs_validate_r6.py, data_store/validation/towns_fund/schema_validation/validate.py
Bug noticed by Craig when he was playing about with rogue input on test. If we have a non-null, non-datetime input in "Start Date" column of "Project Progress" table in TF spreadsheet, we fail completely at the line `if start_date > completion_date` in `funding-service-design-post-award-data-store/data_store/validation/towns_fund/schema_validation/validate.py::validate_project_dates`, with `'>' not supported between instances of 'WRONG_TYPE' and 'datetime.datetime'`.
=> Ensure TF schema validation on project start and end dates handles non-datetime input

scripts/migration-task-script.py
When attempting to make a deployment with AWS Copilot, if the AWS Session Manager plugin is not up-to-date, then user input will be requested to update it, causing the pipeline to fail as the terminal is non-interactive.
This change adds a flag `yes=false` to the `copilot svc exec` command in the migration script to cause it to respond automatically in the negative when the update request is levied, unblocking the pipeline.
Fix identified from: https://github.com/aws/copilot-cli/issues/4627#issuecomment-1470324659
=> Prevent SSM plugin update request during deployment

data_store/validation/towns_fund/schema_validation/validate.py, requirements-dev.in, requirements-dev.txt, tests/integration_tests/test_ingest_component_all_funds.py
Currently we get unpredictable failures in the `test_multiple_rounds_multiple_funds_end_to_end` integration test, which occur when the ingest occurs in the minute before (or multiple minutes before) the expected dataframe for the extract is created. This is because for each ingest, we use `datetime.now` to set the submission date which appears in the extract, and then only after all ingests and the download have taken place do we then use `datetime.now` again to determine the expected values in the extract. The test passing is currently reliant on the first and last calls to `datetime.now` happening before the minute mark ticks across.
You can observe the failure happening 100% of the time if you add a sleep call of 60 seconds just after all ingest calls in the test function.
This change …
=> Using freezegun to freeze time in integration test to fix occasional minute-rounding mismatch error

data_store/controllers/ingest.py, data_store/controllers/ingest_dependencies.py, data_store/table_extraction/config/common.py, data_store/table_extraction/config/pf_r1_config.py, data_store/table_extraction/config/pf_r2_config.py, data_store/table_extraction/extract.py, data_store/table_extraction/process.py, data_store/validation/pathfinders/schema_validation/validate.py, tests/data_store_tests/table_extraction_tests/test_extract.py, tests/data_store_tests/test_full_pf_pipeline.py, tests/data_store_tests/validation_tests/pathfinders/schema_validation_tests/test_pf_schema_validate.py
For Pathfinders, we use a single schema to configure extraction of 'tables' from spreadsheet worksheets, processing of those tables to create clean, labelled DataFrames, and validation of those cleaned DataFrames using Pandera. Currently, the schema is a plain Python object. This change introduces new classes for representing the objects and sub-objects that form the schema, and uses those new classes in the schema.
=> BAU - reifying Pathfinders schemas for extraction, processing and validation

data_store/db/entities.py
Ticket:
https://dluhcdigital.atlassian.net/browse/FPASF-588
Description:
We have already made the Submission model's ingest_date column nullable and stopped writing to it. 
This PR is for dropping the column.
=> Drop ingest_date column

data_store/controllers/mappings.py, data_store/db/entities.py, data_store/db/queries.py, data_store/serialisation/data_serialiser.py, data_store/transformation/pathfinders/pf_transform_r1.py, data_store/transformation/pathfinders/pf_transform_r2.py, data_store/transformation/towns_fund/tf_transform_r3.py, data_store/validation/towns_fund/schema_validation/schemas.py, find/templates/find/main/data-glossary.html, tests/data_store_tests/db_tests/test_entities.py, tests/data_store_tests/serialisation_tests/test_serialisation.py, tests/data_store_tests/transformation_tests/towns_fund/resources/assertion_data/round_three/organisation_ref_expected.csv, tests/integration_tests/mock_tf_r3_transformed_data/Organisation_Ref.csv, tests/integration_tests/test_ingest_component_all_funds.py, tests/integration_tests/test_ingest_db_transactions.py, tests/resources/organisation_dim.csv
Ticket:
https://mhclgdigital.atlassian.net.mcas.ms/browse/FPASF-609
(please see Gideon's comment to drop "geography" column).
Description:
This PR is part 1 to drop the "geography" column from the "Organisation" model. 
We've never used it, it was set to None during ingest. 
It was used in tests only. 
This PR: 
- removes the column from the model, 
- removes it from mappings and lookups,
- removes it from data serialisation, 
- removes it from tests and from some doctstrings, where it wasn't actually used,
- removes it from test csv setup files,
- removes it from other places, where it was "used". 
Note that the DB migration tests are failing. Migration file will follow.
=> Drop geography column from Organisation model

tests/e2e_tests/test_submit.py
Issue caused by new R2 success file using 'Bolton Council' as org, not 'Test Council' as previously.
=> Fix broken E2E test for Pathfinders submission

data_store/controllers/ingest.py, tests/integration_tests/test_aws.py
Fixes the recent Sentry error caused by uploading files with non-aschii names. 
The change make it so we no longer use the user submitted file name on AWS upload.
The user confirmation email will still show the user submitted file name. 
Use a file with non-aschii chars and try to submit it.
=> Fix non aschii filename error

renovate.json
Pulls renovate config from a shared central repository ([communitiesuk/renovate-config](https://github.com/communitiesuk/renovate-config/blob/main/default.json)). The main difference this adds, for now, is that it will group updates for ruff in Python and pre-commit together, because otherwise it's annoying.
=> Extend from shared renovate config

data_store/controllers/ingest.py, data_store/controllers/retrieve_submission_file.py, find/main/routes.py
https://mhclgdigital.atlassian.net/browse/FLS-788
When a Local Authority (LA) submits their return, we send the fund team a link to download the file. If the LA re-submits the file, the old submission is removed, and the fund team gets an error because the submission_id has changed.
To fix this, we now store the filename in the `download_filename` metadata when the file is uploaded. This way, we can use the metadata to retrieve the file instead of relying on the database. For older files, if the new metadata is missing, we use a custom fallback name to ensure the file can still be accessed.
=> Update Spreadsheet Retrieval using Metadata

data_store/controllers/ingest.py, tests/integration_tests/test_aws.py, tests/submit_tests/test_utils.py
When a user uploaded a file with a non-ASCII safe filename, it caused an error in our system (logged on Sentry).
To address this, I made the following updates:
When a file is uploaded, we first try to make the original filename ASCII-safe.
If for any reason the filename cannot be sanitised e.g., it contains characters that can’t be converted to ASCII, the system automatically falls back to a user-friendly, filename.
This ensures that file uploads will always work smoothly, even when the original filename contains problematic characters. Users will either get an ASCII-safe version of the original filename or a simple, readable fallback name.
=> Making ascii safe filenames for submission

data_store/validation/pathfinders/cross_table_validation/common.py
It turns out in some situations the cell is not a string. So `.lower()` throws a 500.
This is blocking PF submissions.
=> Force str type

app.py, pyproject.toml, uv.lock
We used to hack around utils not supporting healthchecks on flask apps that were in `host_matching` mode, but as of v5.3.0 utils now support both `host_matching` and non-`host_matching` mode.
So let's pull that in and drop our workaround.
=> Pull in latest utils for any-host healthcheck

find/main/routes.py, tests/find_tests/test_routes.py
We received a [support ticket](https://mhclgdigital.atlassian.net/jira/servicedesk/projects/FSDS/queues/custom/44/FSDS-636) from the Towns Fund team. They reported that they couldn't download a file from the submission of one of the Local Authorities (LA) in their Towns Fund mailbox. After looking into it, I discovered that the LA's Organisation Name had a comma (,) in it. This was causing an issue when trying to fetch the file from the server.
Even though we’re not using the original filename from the LA, we generate our own filenames by including the Organisation Name to make it more user-friendly. The problem occurred when we tried to download the file using a presigned URL from AWS S3. The comma in the organisation name was getting encoded into something like %2C in the URL, but this …
=> FLS-807-retrieve-spreadsheet-issue

find/scripts/extract_download_logs.py
https://mhclgdigital.atlassian.net/browse/FSPT-207
The account-store endpoint 400s/500s if there are no account IDs to resolve, which breaks this script.
If there are no account IDs, let's shortcircuit that bit.
=> Don't call API if there are no users

find/scripts/extract_download_logs.py
We should be sending these as multiple query params, not as a comma-separated values in a single query param.
=> Fix multiple account IDs for bulk-account endpoint

data_store/controllers/ingest.py, data_store/controllers/ingest_dependencies.py, tests/integration_tests/test_ingest_metrics.py
**Ticket:**
https://mhclgdigital.atlassian.net/browse/FLS-909
**Description:**
PF Team requested to make an exception for Stockton-on-Tees Borough Council, to allow them submitting negative values in the spreadsheet's "Finances" tab. 
**How to test:**
1. In config.envs.development.py, to class DevelopmentConfig, add:     "Stockton-on-Tees Borough Council”   to PF_ADDITIONAL_EMAIL_LOOKUPS[domain] to be able to submit the test spreadsheet:
PF_ADDITIONAL_EMAIL_LOOKUPS = {
domain: (("Rotherham Metropolitan Borough Council", "Bolton Council", "Wirral Council", "Test Council", 
**"Stockton-on-Tees Borough Council"**),)
for domain in ("communities.gov.uk", "test.communities.gov.uk")
}
2. Email me to send the test spreadsheet over with the negative values (can't be downloaded from the ticket, or …
=> Allow negative value submit for Stockton

.github/workflows/aws_copilot_deployment.yml
https://mhclgdigital.atlassian.net/browse/FSPT-220
Adds a slack notification if this pipeline fails.
Should not trigger if the pipeline deploy to prod is rejected by a developer, or the pipeline run is cancelled.
=> Add failed deployment notifications

copilot/post-award-celery/manifest.yml, copilot/post-award/manifest.yml, tests/e2e_tests/conftest.py
Migrates dev environment to communities domain
Have deployed and E2E tests pass. https://github.com/communitiesuk/funding-service-design-post-award-data-store/actions/runs/13570984959/job/37936408422
Note Authentication won't work on new domains until pre-award authenticator is also migrated to the communities domain
=> FSPT-228: Migrate to communities domain

copilot/post-award/manifest.yml
Fix after #935 
`AUTHENTICATOR_HOST` was no longer specified on test and prod leading to broken links
Links to sign in should work
=> FSPT-228: restore authenticator host on test and prod

find/scripts/extract_download_logs.py
A recent bump to the version of mypy we use started to flag this type hint error:
find/scripts/extract_download_logs.py:168: error: Argument 1 to "cloudwatch_logs_to_rows" has incompatible type
"list[list[ResultFieldTypeDef]]"; expected "list[list[dict[Any, Any]]]" [arg-type]
Unfortunately we didn't have our type hints CI check down as 'required to pass', so it got auto merged. That's fixed now, and this will make our type checks pass again.
=> Fix type hints after mypy update

copilot/post-award-celery/manifest.yml, copilot/post-award/manifest.yml
update test config to move to test.communities.gov.uk domain
after deploying services should be available on the test.communities.gov.uk domain
=> FSPT-228: update test config to move to communities domain

copilot/post-award/manifest.yml
add communities production aliases ahead of migration
PROD alias should resolve but 404 after deployment.
=> FSPT-228: add communities production alias

copilot/post-award/manifest.yml
I originally set sentry to sample traces at high volume in dev/test/uat, but because of our regular e2e tests (and because we have a low allowance for spans) we're using up our allowance regularly, leading to gaps in our monitoring+observability.
I also don't think many of our team currently use sentry span insights in dev/test/uat in the way I'd intended, so spending our allowance here feels less useful.
Let's monitor prod at 100%, because those are likely to provide more realistic insights (and if there are errors, more information to help debug). The volume there is also significantly lower, so we should not have to worry about hitting our allowances.
=> Flip sentry traces sample rate

data_store/controllers/ingest.py, data_store/controllers/ingest_dependencies.py
Ticket:
https://mhclgdigital.atlassian.net.mcas.ms/browse/FLS-1300
Description:
Loosen Pathfinders return validation for Bolton Council to allow submission of negative values in the Finances tab, in G37
and G51 cells.
This change removes the negative value validation for the columns of these two cells. 
How to test:
Ping me to send the file over and submit that to the portal.
=> Change Pathfinders validation to allow negative values

data_store/controllers/ingest.py
Fixing failed submission handling in the case of `OldValidationError` by setting `excel_file` on the Flask global object `g` so that it is available in the `process_internal_failures` context.
This issue was found during analysis of this Sentry error: https://funding-service-design-team-dl.sentry.io/issues/6635473778/?alert_rule_id=14533929&alert_type=issue&notification_uuid=f7d642bf-46b8-4e43-b79b-d2794824de80&project=4505390859747328&referrer=slack
However that error was actually caused by the fact that one of the project names in the "Funding Profiles" (finances) tab had been overridden by the typo "v". The issue fixed by this PR just meant that the failed submission wasn't successfully saved to the failed submission bucket in AWS S3.
=> Fixing failed submission handling
