core/validation/README.md
core/validation/failures.py
core/validation/schema.py
core/validation/validate.py
schemas/towns_fund.json
tests/validation_tests/test_schema.py
tests/validation_tests/test_validate.py

https://trello.com/c/ZCEVybXJ/207-implement-enum-validation-in-spreadsheet-validator
Adds the ability to define and validate enums.

[#PAB-207] enum validation

---

core/db/entities.py
tests/db_tests/test_entities.py

https://trello.com/c/IiJFjd9v
New model for Project entity

[#PAB-226] Create SQLAlchemy model for Project

---

core/db/entities.py

https://trello.com/c/IiJFjd9v
Models for Outcome and Output (dim and data tables for each)
- [N/A ] Unit tests and other appropriate tests added or updated

[#PAB-226] Models for Output_Dim and Output_Data

---

core/db/entities.py

https://trello.com/c/IiJFjd9v
Added models for:
- Direct Fund Data
- Capital Data
- Indirect Fund Secured Data
- Indirect Fund Unsecured Data

[#PAB-226] Fund and capital models

---

core/db/entities.py

https://trello.com/c/IiJFjd9v/226-create-additional-sqlalchemy-models
Added the final lot of models
- [NA] Unit tests and other appropriate tests added or updated

[#PAB-226] create project delivery plan, procurement and risk register models

---

core/db/__init__.py

Encountered an issue where tables wouldn't always be created when `db.create_all()` was called. This ensures that they're always loaded into the DB.
- [NA] Unit tests and other appropriate tests added or updated

[FIX] load all models to db

---

core/db/entities.py
tests/db_tests/test_entities.py

BAU: (FIX) Add missing package_id to package model

---

core/db/entities.py

Fixes a model that references the wrong Enum class
- [NA] Unit tests and other appropriate tests added or updated

[FIX] incorrect procurement status enum

---

tests/conftest.py
tests/db_tests/resources/db_seed_data.py
tests/db_tests/test_entities.py
tests/util_test.py

https://trello.com/c/pHGBCS8S/228-create-test-seed-script-for-sql-db
- [ X] Unit tests and other appropriate tests added or updated
- [X ] README and other documentation has been updated / added (if needed)
- [X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

[#PAB-228] move test data to seed script in conftest

---

README.md
app.py
core/controllers/ingest.py
core/controllers/mappings.py
tests/controller_tests/conftest.py
tests/controller_tests/test_ingest.py
tests/controller_tests/test_integration.py

https://trello.com/c/S7q0iDUV/227-ingest-spreadsheet-into-sqlite-db
Develop the ingest endpoint so that the SQL DB is populated by the validated workbook.

[#PAB-227] ingest spreadsheet into SQLite DB

---

core/controllers/ingest.py
tests/controller_tests/conftest.py
tests/controller_tests/test_ingest.py
tests/controller_tests/test_integration.py

https://trello.com/c/wGt8Jv9L/287-bug-multiple-calls-to-ingest-endpoint-causes-internal-error
Fixes multiple calls to ingest and adds an integration test

[#PAB-287] fix multiple ingest calls

---

copilot/post-award-data-store/addons/post-award-data-store-cluster.yml

Adds Postgres database for deployment (this is needed in preparation of the ITHC.)
Deploy should be successful

PAB-297: add postgres database

---

copilot/environments/test/manifest.yml

We need to add a Cloudfront distribution to the environment so it is more realistic for the pen test.
Should deploy successfully on merge

 PAB-237: add CDN to environment

---

.gitignore
core/extraction/towns_fund.py
tests/controller_tests/test_integration.py

PAB-318: https://trello.com/c/yCVpmSB1 
Methods to extract data from TF data entry form (Excel file).
Each sheet needs it's own method due to large differences between sheets. Each extracted added to it's own dataframe, which are attached to a dict. 

[PAB-318] Ingest data from Towns Fund spreadsheet

---

app.py
core/cli.py

https://trello.com/c/XriMEDz1/361-prep-api-for-pen-test
Seed the database on start-up with some test data because the ingest endpoint is inaccessible in the test environment.

[#PAB-361] seed db on startup

---

core/cli.py

https://trello.com/c/SQX3xWte/363-create-cli-command-to-test-db
Adds a flask CLI command to test if the db was initialised successfully.
`flask seed-test` to run the test
should fail if ran before `flask seed` and pass if run after.

[#PAB-363] add seed test

---

.github/workflows/deploy.yml

We need to seed data after deployment, so it is not wiped after each merge.
Data should be available post-deployment
Deploy should complete successfully

BAU: seed data after deployment

---

app.py
config/__init__.py
config/envs/default.py
config/envs/development.py
config/envs/unit_test.py
core/cli.py
requirements-dev.txt
requirements.in
requirements.txt

https://trello.com/c/zZ7XRHeA/295-setup-postgres-database
Add configuration options to connect to prostgres db. Also adds a new CLI command to drop all data from the database.

[#PAB-295] use postgres db

---

config/__init__.py
config/envs/test.py
copilot/data-store/manifest.yml

Add required postgres connection string for AWS 
Deployment should work
Should connect to Postgres instance on AWS

PAB 297: add postgres connection string for AWS

---

core/extraction/towns_fund.py

[#PAB-331] https://trello.com/c/97RfNJ9h
Project Details DataFrame transformed to match "Load" format (minus submission id) for ingestion into DB.
Changes in PR:
+++ Project id lookup table extracted from form
+++ lookup project id on project details DataFrame 
+++ Squash multiple/single columns together

[#PAB-331] R3 Transformation: Project Details

---

config/envs/default.py
core/cli.py
tests/conftest.py
tests/controller_tests/conftest.py
tests/controller_tests/test_ingest.py

Add data model example ss to the config and modify all paths to reference it.

[BAU] ref a single example data model path

---

core/extraction/towns_fund.py

- Calculate programme id
- populate programme info ingest table
- add  programme id to project ingest table

[#PAB-332] Transform round 3 programme Data

---

core/extraction/towns_fund.py

- Tidied up references to match "load" mapping names
- Transformed Organisation_ref ready to load
- Transformed Programme Progress ready to load

[#PAB-332] Transform round 3 Organisation and Programme Progress data

---

core/db/entities.py
core/extraction/towns_fund.py
core/validation_schema.py

Transform `Programme Progress` ready to load into DB
Transform `Funding Question` ready to load
Minor change to nullability on funding Q DB schema

[#PAB-332] Transform round 3 Project Progress and Funding Questions

---

core/controllers/get_filters.py
openapi/api.yml
openapi/components.yml
tests/controller_tests/test_filters.py

Added function to get a list of organisation names from the database for the frontend filter.

#PAB-421: added function for getting organisation names for filter

---

core/const.py
core/controllers/get_filters.py
openapi/api.yml
openapi/components.yml
tests/controller_tests/test_filters.py

https://trello.com/c/V4ZxyIjZ/422-data-store-get-endpoint-to-get-list-of-funds
Endpoint for the front end to acquire the list unique funds in the database.

[#PAB-422] get funds endpoint

---

scripts/ssm-conn.sh

Co-authored-by: Aaron Williams <aaron.williams@version1.com>
Adds script to tunnel to container.
(this will be used as the initial approach to POST to the ingest endpoint
on the api)
Requires AWS access but have confirmed it works as described.

BAU: Adds script to create tunnel to container

---

core/const.py
core/controllers/download.py
core/db/entities.py
core/serialization/download_json_serializer.py
core/util.py
openapi/api.yml
tests/controller_tests/test_download.py
tests/db_tests/test_queries.py

https://trello.com/c/oGoXGIS2/429-download-endpoint-filtering-capability
Adds query params to download endpoint. Also adds all the proper database querying functionality and serialising, replacing the existing example dummy query and output.

[#PAB-429] download endpoint filtering and serialization 

---

core/controllers/get_filters.py
openapi/api.yml
openapi/components.yml
tests/controller_tests/test_filters.py

https://trello.com/c/oluqlVNU/426-endpoint-list-of-outcome-categories
Implements a GET endpoint for the frontend to get all the possible outcome categories in the data.

[#PAB-426] get outcome categories endpoint

---

core/controllers/ingest.py
core/db/entities.py
core/extraction/towns_fund.py

Improvements to R3 transformation pipeline:
- Removed redundant code
- vectorise some slow iterative methods
- Add TODO comments for parts to review (how and when to consider an input row "empty" and whether to discard it upon ingest)
- Changes to model - nullability on value fields rather than defaulting to 0, to persist the actual value users entered (or didn't)

[#PAB-332] DB model changes and R3 transformation improvements

---

.github/workflows/deploy.yml

* Adding in workflow dispatch
* Adding in aws config to utilise OIDC
* Updating credentials action version
* Adding session name
+ref: PAB-400
+semver: minor
Updating Deploy workflows to use the new AWS accounts

Updating the deploy workflow to include production

---

core/controllers/get_filters.py
openapi/api.yml
openapi/components.yml
tests/controller_tests/test_filters.py

https://trello.com/c/ymSf5kaR/445-endpoint-list-of-regions
Regions endpoint for frontend to receive regions for filters.

[#PAB-445] regions endpoint

---

tests/db_tests/test_entities.py
tests/db_tests/test_queries.py

Remove unnecessary flush calls to db

BAU_ FIX: remove flush calls

---

core/extraction/towns_fund.py

BAU_
Fix to prevent key errors on data mappings in pipeline, changed v3.0 of form.
Also fixed some minor inconsistent drop row behaviour in outcomes

BAU_ FIX: Upgrade R3 Ingest pipeline to form V3.0

---

core/const.py

Enum values were missing Likelihood = "4 - Almost Certain"

[FIX] add missing Likelihood enum value

---

core/db/entities.py

Funding Comment table now accepts null comments

[FIX] FundingComment comment now nullable

---

core/controllers/ingest.py
core/validation/failures.py
core/validation/schema.py
core/validation/validate.py
core/validation_schema.py

adds non-nullable constraint to validation. Will pick up any null values that shouldn't be null. Also allows us to turn on enum validation again.

[BAU] add non-nullable constraint to validation

---

core/extraction/towns_fund.py

Fix ingestion of High Street fund submissions

[FIX] ingest High Street fund submissions

---

scripts/batch_ingest.py

Script to automate ingestion of a directory of submission files.

[BAU] automate ingest script

---

core/validation_schema.py

[BAU] FundingComment.comment should be nullable in validation schema

---

core/validation/schema.py
core/validation/validate.py
core/validation_schema.py
tests/validation_tests/test_validate.py

adds the concept of nullable tables

[BAU] table_nullable added to validation

---

.github/workflows/deploy.yml

Adds step to run database migrations
Should run successfully post-merge

PAB-400: run migrations before deployment

---

core/const.py
core/validation_schema.py

Validates incoming fund type IDs against an enum class during validation

[BAU] add Fund Type ID enum validation

---

copilot/data-store/addons/data-store-cluster.yml
copilot/data-store/manifest.yml

Tweaks to make the environment more production ready
Will be deployed manually initially for the encryption change, then normal deploys can resume via CI.

PAB-400: update settings for production deployment

---

scripts/ssm-conn.sh

Updating ssm bash script to be a little more user friendly
+semver: minor
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ N/A ] README and other documentation has been updated / added (if needed)
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

BAU_Updating bash script

---

Dockerfile

Increase gunicorn worker timeout from 30 to 60 seconds.

[BAU_FIX] increase gunicorn worker timeout

---

core/extraction/round_two.py

https://trello.com/c/ft3h4jcP
+++ transformation of Submission
+++ transformation of Place Details
+++ Simplified lookups for Project, Submission and Programme ID's

[#PAB-333] Transform round 2 Submission, Place details

---

core/extraction/round_two.py
core/extraction/utils.py
tests/extraction_tests/utils_tests.py

https://trello.com/c/ft3h4jcP
Transform (ready for load):
+++ Project Details
+++ Programme Ref
+++ Organisation Ref
+++ Programme Progress
+++ Project Progress
+++ Util to convert pandas series from Excel to Python datetime

[#PAB-333] Transform round 2 project, programme and related tables

---

core/const.py

[BAU_FIX] align geo indicator enum with submission enum

---

core/controllers/ingest.py
tests/controller_tests/test_ingest.py

Previously, upsert (merge) only worked if an incoming programme had already been added in the same round. 
It now does it if one was added in this or any prior round (but not subsequent ones). Previously, this gap caused a unique error constraint
Unit test added for this specific case

BAU_ FIX: Upsert on Programme to include PREVIOUS rounds' programmes

---

core/extraction/round_two.py

https://trello.com/c/ft3h4jcP
+++ transform funding questions
+++ transform funding profiles/data
NOTE: no funding comments added, as they are not provided with Round 2 data

[#PAB-333] Transform round 2 funding comments and data tables

---

core/validation_schema.py

Enable Yes/No enum check for GIS attribute on Project data

[BAU_FIX] add additional enum check to project validation

---

core/util.py

Cast location data to string before regex - fixes run time error on ingest

[BAU_FIX] cast location data to string before extracting postcodes

---

.gitignore
app.py
config/envs/default.py
core/controllers/download.py
core/db/entities.py
core/db/queries.py
core/serialization/download_json_serializer.py
tests/db_tests/test_queries.py

Main change:
Removes reliance on inefficient lazy loading of child models (submission and project/programme) during serialization. This was causing excessive calls to the DB during each iteration of list comprehensions. We now pre-load this data in prior queries. 
Performance testing suggests it reduces run times by 50%. Massively reduces the number of queries sent to the db.
Additional change:
Adds the option to run the application with a profiler enabled to track python execution times.

/download endpoint query optimisation

---

.gitignore
core/extraction/round_one.py
openapi/components.yml
tests/controller_tests/test_integration.py

This is all transformations for Round 1. It makes no alteration to the ingest file, which is where loading behaviour will be coded. It provides a function to extract & transform Round 1 data, and has no interaction with the rest of the programme. 

[BAU] all transformations for Round 1

---

config/envs/default.py
core/controllers/ingest.py
core/controllers/mappings.py
core/extraction/round_one.py
core/validation_schema.py
openapi/components.yml

- Loading of Round One data for TF
- Slight alterations to Round One transformations

[#PAB-391] Round One Load

---

core/extraction/round_two.py

Completed transformations for Output Data for Round 2. 
**Test**
Testing can be conducted by running test_ingest_round_two_historical() in Pycharm and inspecting the resulting dataframe with an appropriate breakpoint.

Transform Round 2 Output Data

---

core/db/entities.py
core/serialization/download_json_serializer.py

Adds programme ids to the project details tab/section of the download output

[BAU_FIX] add programme id to project details download output

---

core/extraction/round_two.py

Can deduce actual/forecast columns from start and end date columns vs. last day of R2 reporting.
Set break point at appropriate line, run test_ingest_round_two_historical(), inspect df_outputs to ensure "Actual/Forecast" column is accurate.

BAU: get actual/forecast for R2

---

core/controllers/download.py
core/serialization/download_json_serializer.py
core/serialization/download_xlsx_serializer.py
tests/test_serialization.py

Restore these changes.
Reverts communitiesuk/funding-service-design-post-award-data-store#170

Revert "Revert "Feature/360 model extract tab updates""

---

core/extraction/round_two.py
tests/controller_tests/test_integration.py

Transformation for Outcomes.
Set breakpoint at relevant point & inspect df.

Transform Round 2 Outcomes

---

Dockerfile
config/envs/default.py
core/const.py
core/controllers/ingest.py
core/extraction/towns_fund_round_one.py
core/extraction/towns_fund_round_two.py
core/validation_schema.py
openapi/components.yml
tests/controller_tests/test_historical_ingest.py
tests/controller_tests/test_integration.py
tests/extraction_tests/test_historical_extraction.py

Loading for Round 2. Includes unit tests, refactoring of ingest, and appropriate schema changes.

Load Round Two

---

core/const.py
core/controllers/download.py
tests/controller_tests/test_download.py

https://trello.com/c/ufs7Pm8S/578-implement-data-sorting-on-the-data-extract
- The data from the downloaded spreadsheet should now be sorted by the columns in order of preference as detailed in const.py

[#PAB-578] sort data extract excel file

---

core/validation/README.md
core/validation/failures.py
core/validation/validate.py
core/validation_schema.py
tests/validation_tests/test_validate.py

[Trello Ticket](https://trello.com/c/xclaqIcd/511-unique-together-validation)
Added Function, tests for unique together validation
Run tests

511 Add composite_key validation

---

core/const.py
core/controllers/ingest.py
core/errors.py
core/util.py
core/validation/failures.py
core/validation/validate.py
tests/validation_tests/test_failures.py
tests/validation_tests/test_validate.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?modal=detail&selectedIssue=SMD-38
- Adds a new Abstract Base Class for validation Failures to implement user centred validation messages
- Adds an option to return only user-centred validation messages on unsuccessful ingestion

[SMD-38] adds unused dropdown user-centered validation messages

---

core/const.py
core/controllers/ingest.py
core/errors.py
core/validation/failures.py
core/validation/initial_check.py
tests/validation_tests/test_failures.py
tests/validation_tests/test_pre_checks.py

- UC messages for pre-transformation failures
- Refactoring of code to incorporate extraction of R4 submission details

[SMD-52]: pretransform uc messages

---

core/controllers/download.py
core/serialisation/data_serialiser.py
tests/serialisation_tests/test_serialisation.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/FMD/boards/139?modal=detail&selectedIssue=FMD-47
Switching serialise_download_data to be a Generator rather than a function reduces the memory usage of Python when transforming query data into Excel sheets (as it now only "lazily loads" data from each table query as it is added in, rather than holding it all in memory at once)
Reduced specific test case of all R2 data only, from 40.8s (avg) to 32.4s (avg)
Deploy to TEST, set some filters, download and check file

[FMD-24] Optimisation - switch main serialisation function to generator

---

tests/validation_tests/test_validate.py

Fixes issues with our validation tests, some of which we indented out and so not being run on push.

BAU: fix broken tests

---

.github/workflows/deploy.yml

Workaround for regression in: https://github.com/aws/copilot-cli/issues/5265
Will re-test deploy after merge

BAU: pin to previous version of copilot

---

core/const.py
core/validation/failures.py
tests/validation_tests/test_failures.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?selectedIssue=SMD-40
- Adds support for additional dropdown failure scenarios
- Refactors dropdown test cases to test the conversion of failure -> uc components in isolation

SMD-40 Dropdown validation fix and additional test cases

---

app.py
core/const.py
core/errors.py
core/validation/exceptions.py
core/validation/failures.py
openapi/api.yml
openapi/components.yml
tests/controller_tests/test_ingest.py
tests/extraction_tests/test_round_three_extraction.py
tests/validation_tests/test_failures.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?selectedIssue=SMD-5
Switches the validation output to new user-facing messages.

[SMD-5] enable user facing validation messages

---

core/extraction/towns_fund.py
core/validation/failures.py
tests/extraction_tests/test_round_three_extraction.py
tests/validation_tests/test_failures.py

New user-friendly validation messages for InvalidOutcomeProjectFailure: https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?selectedIssue=SMD-103

[SMD-103]: project outputs failure uc message

---

core/controllers/ingest.py
core/validation/specific_validations/towns_fund_round_four.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?selectedIssue=SMD-68
Initial PR to define the framework around which we will collect Round 4 specific validations that don't fit into the existing `validation` package generic flow.

[SMD-68] add framework for collecting round 4 specific validations

---

core/validation/specific_validations/towns_fund_round_four.py
tests/validation_tests/test_tf_r4_specific_validations.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?selectedIssue=SMD-110
Adds the validation functionality to check that each submission contains at least 3 programme level risks.

[SMD-110] programme level risk validation

---

core/errors.py
openapi/api.yml
tests/controller_tests/test_ingest.py

Validation Error status code 440 -> 400

Revert validation error status code change

---

copilot/data-store/manifest.yml
requirements-dev.txt
requirements.in
requirements.txt

https://dluhcdigital.atlassian.net/jira/software/c/projects/FMD/boards/139?modal=detail&selectedIssue=FMD-50
Upgrades the version of the utils package to latest, adds an env var to the Copilot config which increases profiler sampler rate to 1.0 in the test environment.

Fmd 50/sentry env var

---

core/validation/specific_validations/towns_fund_round_four.py
tests/validation_tests/test_tf_r4_specific_validations.py

Merged the last PR without pushing a final change to it.

[SMD-67] fix programme risk validation message

---

core/validation/specific_validations/towns_fund_round_four.py
tests/validation_tests/test_tf_r4_specific_validations.py

https://dluhcdigital.atlassian.net/browse/SMD-68
- Implements a requirement change whereby completed projects do not need to adhere to the 1 risk per project validation

[SMD-68] fix project risks validation

---

core/controllers/ingest.py
core/validation/specific_validations/towns_fund_round_four.py
openapi/components.yml

https://dluhcdigital.atlassian.net/browse/SMD-156
- Adds documentation update to accompany Joel's previous PR
- disables sign off validation as it's currently got a bug

[SMD-156] backend authorisation

---

copilot/data-store/manifest.yml

Bump CPU as some tasks appear to the be CPU constrained (note memory has also to be bumped as it needs to be a valid combination as described in: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html)
Should deploy successfully post-merge

BAU: bump CPU and memory

---

app.py
core/errors.py
core/validation/exceptions.py
tests/controller_tests/test_ingest.py

https://dluhcdigital.atlassian.net/browse/SMD-142
- handle uncaught ingest exceptions
- leaves placeholder for saving the submission to S3 storage

[SMD-142] log failed ingest

---

core/extraction/towns_fund.py
core/validation_schema.py
tests/extraction_tests/resources/assertion_data/funding_data_expected.csv
tests/extraction_tests/resources/mock_sheet_data/funding_profiles_mock.csv
tests/extraction_tests/resources/mock_sheet_data/project_identifiers_mock.csv
tests/extraction_tests/test_round_three_extraction.py

Deal with the conditional formating in the funding profiles tab of the TF spreedsheet. There are a number of cells on this tab that are covered by a grey box dependant on a number of conditions on page. This PR is to drop these cells from the data extract going forward with round 3 and 4 data extracts.
There are 3 main considerations:
1. all cells for before 2020 are greyed out except for "Other funding sources"
2. if fund type is Town Deal and Programme only is selected the question: "How much of your CDEL forcast is contractually commited" is greyed out
3. if fund type is Future High Street Fund:
a. Section B is not required
b. "5% CDEL pre-payment", "RDEL payment", and "How much of your RDEL is commited" are not required
c. Payment for reporting period is only required forcasted half a …

[SMD-120] Remove Unneeded FSHF Data from future ingests

---

core/validation/specific_validations/towns_fund_round_four.py
tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py

Validate that if a funding gap of > 0 is specified in Private funding sources tab that an additional comment is supplied to explain why

[SMD-116] Validate PSI funding gap

---

core/const.py
core/validation_schema.py
tests/validation_tests/test_failures.py

https://dluhcdigital.atlassian.net/browse/SMD-75
- Adds enum validation for Project Adjustment Request Status

[SMD-75] add Project Adjustment Request Status enum validation

---

copilot/data-store/addons/data-store-failed-files.yml
copilot/data-store/addons/data-store-file-assets.yml

* Added failed files s3 bucket addon
* Added file assets s3 bucket addon
+ref: SMD-190
+semver: minor
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ N/A ] README and other documentation has been updated / added (if needed)
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

SMD-190: Add s3 buckets to the data-store

---

core/const.py
core/validation_schema.py
tests/validation_tests/test_failures.py

https://dluhcdigital.atlassian.net/browse/SMD-67
- address bug found during QA where an empty Risk Category cell would cause a KeyError
- also adds enum validation for Risk Category for Round 4

[SMD-67] fix Risk Category validation

---

openapi/components.yml

fixes an incorrectly named ingest endpoint param

[BAU_FIX] fix ingest param definition

---

.github/workflows/deploy.yml

We can revert this now regression has been fixed.
Reverts communitiesuk/funding-service-design-post-award-data-store#215

FMD-38: Revert "BAU: pin to previous version of copilot"

---

core/validation/initial_check.py
tests/validation_tests/test_pre_checks.py

- fixes a bug where we were carrying out pre-validation checks on incompatible historical data rounds

[BAU] fix historical data ingest

---

.github/workflows/deploy.yml
README.md

Add dev environment option so it can be deployed to manually
Have tested by deploying from this branch in: https://github.com/communitiesuk/funding-service-design-post-award-data-store/actions/runs/6497519823/job/17646812805

FMD-37: add dev environment

---

core/const.py

- accept the latest template version

[BAU] upversion accepted Round 4 template

---

.github/workflows/deploy.yml

Reverts communitiesuk/funding-service-design-post-award-data-store#285

Revert "[BAU] turn off automatic deployment of main branch"

---

core/validation/specific_validations/towns_fund_round_four.py

- Programme Ref rows are not always 0 indexed - the change uses iloc to retrieve the first row regardless of index

[BAU] fix index error during validation

---

app.py

- modifies a log statement to only capture the SQL backend type from the URI
- [] Unit tests and other appropriate tests added or updated
- [] README and other documentation has been updated / added (if needed)

[BAU] only log SQL backend type from URI

---

copilot/data-store/addons/data-store-file-assets.yml

Update env var to expected name, needs to match: https://github.com/communitiesuk/funding-service-design-post-award-data-store/blob/9a19c508d2945fae2e3a9cc90f89de436eab6e17/config/envs/default.py#L21
Will test after deployment

BAU: Update S3 env var

---

core/const.py
core/handlers.py
core/util.py
core/validation/failures.py
core/validation/specific_validations/towns_fund_round_four.py
openapi/api.yml
openapi/components.yml
tests/controller_tests/test_ingest.py
tests/validation_tests/test_failures.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-247
Changes the format ValidationErrors to make them a flat dictionary of arrays as described in the ticket. The openapi files have also been updated to show the new structure, along with the tests.

Feature/smd 247/update validation error

---

core/extraction/towns_fund_round_one.py

* fixes issue with the name changes in the mapping's variables
* standardises date time fields in Round 1 to match Round 2
* remove two unneeded columns in Round 1

BAU: fix historical ingest bug

---

.github/workflows/deploy.yml
config/__init__.py

Previously flask env was named 'test' on both 'dev' and 'test' which made it difficult to differentiate e.g. in Sentry
This creates the concept of a dev environment.
Should set dev FLASK_ENV when deployed to dev, other envs will behave as before.

BAU: differentiate dev env

---

core/serialisation/data_serialiser.py

Mostly these are queries which export a lot of data. Note that though this setting can be set on the whole cluster, there is plenty of advice not to set it at that scope and instead to use either transaction or database level. In this case we set it on the txn level.
See the section titled _Considerations_ in
https://aws.amazon.com/blogs/database/tune-sorting-operations-in-postgresql-with-work_mem/
Jira ticket: https://dluhcdigital.atlassian.net/browse/FMD-103

Override work_mem for queries known to be slow

---

.github/workflows/deploy.yml

disable continuous deployment
We need to disable continuous deployment during the pen test
Should not trigger a deploy on merge

BAU: disable continuous deployment

---

core/controllers/ingest.py
core/db/utils.py
tests/controller_tests/test_ingest.py
tests/db_tests/test_queries.py

Fixes the issue whereby two users could not simultaneously submit a return.

[SMD-228]: db load concurrency bug

---

core/validation/failures.py
tests/validation_tests/test_failures.py

Removes validation messages for cells already caught by a null ingest.

remove errors already caught by null failure

---

core/validation/specific_validations/towns_fund_round_four.py
tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py

Makes funding secured not nullable for other funding types

[SMD-319]: make funding secured not nullable for other funding types

---

core/validation/specific_validations/towns_fund_round_four.py
tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py

https://dluhcdigital.atlassian.net/browse/SMD-278
- fixes parsing of real funding allocation file
- also includes a fix for the funding secured nullable validation

[SMD-278] fix use of real funding allocations

---

core/controllers/ingest.py
core/validation/__init__.py
core/validation/failures.py
core/validation/initial_check.py

- sign off validation from pre to post transformation validation
- [] Unit tests and other appropriate tests added or updated

[BAU] sign off validation to post-transformation validation

---

core/const.py
core/validation/failures.py
core/validation/messages.py
tests/validation_tests/test_failures.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-323
Moving the errors away from const.py and adding the updated errors into a similar structure in messages.py. 

[SMD-323] validation error updates

---

core/extraction/towns_fund_round_three.py
core/validation/failures.py
tests/extraction_tests/resources/assertion_data/round_three/outcomes_data_expected.csv
tests/extraction_tests/resources/assertion_data/round_three/outcomes_ref_expected.csv
tests/extraction_tests/test_round_four_extraction.py
tests/extraction_tests/test_round_three_extraction.py
tests/validation_tests/test_failures.py

Present cells of errors from footfall outcomes to users.

[SMD-256]: cells for footfall outcomes

---

core/validation/initial_check.py
tests/validation_tests/test_pre_checks.py

- prevents the app from 500 if a random excel is passed - instead shows a friendly message to use the V4.3 template

[BAU] return "Form Version" message on incorrect Excel file

---

core/validation/specific_validations/towns_fund_round_four.py
tests/validation_tests/round_four_specific_validations/test_tf_r4_specific_validations.py

fixes issue whereby a postcode error is always returned

fix postcode bug

---

core/const.py

Fix issue with funding spent validation where column lookup was giving a key error due to an incorrect mapping

BAU: fix fundng profile with high value validation

---

.github/workflows/deploy.yml

Reverts communitiesuk/funding-service-design-post-award-data-store#311

Revert "BAU: disable continuous deployment"

---

core/controllers/ingest.py
openapi/components.yml
tests/controller_tests/test_ingest.py

https://dluhcdigital.atlassian.net/browse/SMD-343
- adds param to disable load for an ingest request

[SMD-343] add ingest param to disable load

---

core/const.py
core/validation/failures.py
core/validation/utils.py
core/validation/validate.py
tests/controller_tests/test_ingest.py
tests/test_misc.py
tests/validation_tests/test_failures.py
tests/validation_tests/test_validate.py

Reverts communitiesuk/funding-service-design-post-award-data-store#344

Revert "[SMD-336]: accurate cell mappings for outcomes amount col"

---

core/validation/initial_check.py
tests/validation_tests/test_pre_checks.py

Fixes bug whereby a null place name caused an error.

BAU: fix null place name bug

---

core/validation/specific_validations/towns_fund_round_four.py

this function had been erroneously removed from this tuple of validations to run
- enables validate funding questions validations 

[BAU] enable validate funding questions

---

core/db/utils.py
tests/db_tests/test_queries.py

Refactors logging for the transaction_wrapper such that it no longer logs a message every time a retry happens.

BAU: refactor logging of transaction wrapper

---

core/const.py

https://dluhcdigital.atlassian.net/jira/servicedesk/projects/FSDS/queues/custom/44/FSDS-244
- adds HS to Walsall in the PLACE_TO_FUND_TYPE mapping

[BAU] add HS to Walsall in the PLACE_TO_FUND_TYPE mapping

---

core/validation/pre_transformation_validate.py
openapi/components.yml

Adds a default value in the ingest API for auth.

add auth default to api

---

core/controllers/ingest.py
tests/conftest.py
tests/controller_tests/test_download.py
tests/controller_tests/test_filters.py
tests/controller_tests/test_historical_ingest.py
tests/controller_tests/test_ingest.py
tests/controller_tests/test_misc.py
tests/db_tests/test_queries.py
tests/integration_tests/test_ingest_component.py
tests/serialisation_tests/conftest.py
tests/test_handlers.py

Additional work that came out of https://dluhcdigital.atlassian.net/browse/FMD-139 
+++ Switched scope to only drop/build new tables at session scope 
+++ Fixtures to delete DB data rather than rebuilding tables 
+++ More appropriate scoping of all fixtures/tests 
++ Updated fixture docstrings with intended use patterns

Refactor test Fixture Scope

---

core/controllers/ingest.py
tests/controller_tests/test_ingest.py
tests/integration_tests/test_ingest_component.py

Add tests for the method ```parse_auth```.

BAU: testing for parse auth

---

core/const.py

- fix Sutton place to fund mapping

[BAU] fix Sutton place to fund mapping

---

core/const.py

- adds TD to Bishop Auckland PLACE_TO_FUND_TYPE mapping

[BAU] add TD to Bishop Auckland PLACE_TO_FUND_TYPE mapping

---

copilot/data-store/addons/data-store-cluster.yml

Sets additional settings on the database to improve the disaster recovery behaviour.
Have run on dev environment

FMD-146: backup & deletion policy

---

scripts/validation-spike.py

- script documenting the spike
- spike aiming to apply schema based validation to the original spreadsheet structure
- the aim of this is to remove ALL spreadsheet specific logic - meaning we should only have to define a schema per new spreadsheet for all DROPDOWN, EMPTY, UNIQUE and TYPE errors

[SMD-402] new validation spike

---

core/extraction/towns_fund_round_two.py

Fixes a bug pertaining to a type error on the RAG columns in Project Progress.

BAU: fix R2 rag type bug

---

copilot/data-store/addons/data-store-cluster.yml

Adds security group to allow ingress from bastion host
Will test connectivity post-deployment

FMD-221: add bastion security group

---

copilot/data-store/addons/data-store-cluster.yml
copilot/environments/dev/manifest.yml

Create dev environment
Service should deploy post-merge

FMD-194 create dev env

---

scripts/migration-task-script.py

As a large migration was failing with code 137, we need to bump the task memory
Have deployed on dev and check migration task runs successfully

BAU: bump migration task memory

---

scripts/re-ingest.py

- updates re-ingest script to work with `/retrieve` endpoint changes

[BAU] re-ingest script can pull files from db or s3

---

core/validation/initial_validation/validate.py
openapi/api.yml
tests/integration_tests/test_ingest_component.py

- `initial-validation` skips auth checks if no auth details are passed

[BAU] do not run auth checks if no auth is passed

---

copilot/data-store/addons/data-store-successful-files.yml
tests/integration_tests/test_retrieve_submission_file.py

We want to allow list action in order to return an appropriate error if key not found.
Will test after deployment that NoSuchKey exception is thrown

FMD-156: Allow list action

---

core/controllers/retrieve_submission_file.py
tests/integration_tests/test_retrieve_submission_file.py

- Edge case of developers searching for s3 file for an existing DB submission but not corresponding s3 file exists
- Add custom 404 and error to highlight this issue rather than generic NoSuchKey error from S3
- Update unit test to assert behaviour returns custom message

FMD-156: Add custom 404 when no S3 file matching DB submission

---

scripts/migrate_db_files_to_s3.py
tests/integration_tests/test_scripts.py

- Add python script to migrate all existing submission files stored in the Submission table to the successful files S3 bucket. Script includes instructions for running locally.
- Add unit test to test script functionality

FMD-225: Add script to migrate all DB files to S3

---

scripts/migrate_db_files_to_s3.py

Small change to fix db to s3 migration script docstring - fix example command to use underscores instead of hyphens.

FMD-225: Update db to s3 migration script docstring

---

openapi/api.yml

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-637
Simple PR to convert the fixed enum values for reporting_round to a user input integer.
Reporting rounds which are not available for a particular fund should return a validation error

SMD-637 replace enum with int for reporting round

---

core/const.py
core/db/queries.py
core/serialisation/data_serialiser.py
tests/serialisation_tests/test_serialisation.py

adds submission metadata to serialisation
SubmissionRef tab should appear on download

FMD-250: add submission metadata to serialisation

---

core/db/entities.py

Re-ordering model definitions for DB tables, to make it easier to find stuff

[BAU] reorder db table definitions

---

.github/workflows/test.yml

Previously we did not specify the version of images that were used, this means the versions used by the tests didn't match those we were using in the deployed environments which risks erroneous discrepencies.
Tests should pass in CI

BAU: pin test service image versions

---

scripts/re-ingest.py

Couple of tweaks to re-ingest script found in the course of another ticket 
(see commit messages for details)
Run against test env with files argument. Saved files should not have junk characters at start or end

BAU: tweaks to re-ingest script

---

core/table_configs/pathfinders/round_1.py

Remove duplicate pathfinders error messages.

BAU: Remove duplicate pathfinders error messages

---

core/validation/initial_validation/checks.py
core/validation/initial_validation/schemas.py
core/validation/initial_validation/validate.py
tests/integration_tests/test_ingest_component_all_funds.py

Adds a new ```SheetCheck``` to return useful error message if admin sheet not present for specified fund.

BAU: return error for invalid excel submission

---

core/metrics.py
tests/conftest.py
tests/integration_tests/conftest.py
tests/test_core_metrics.py

And also just take a super defensive approach to reporting metrics - if anything fails, still return a response to the user.

Handle no cell index references in metrics reporting

---

copilot/data-store/addons/data-store-cluster.yml

enable performance insights on db instance, to better enable DB query performance analysis.
Have tested by deploying on dev environment and confirming in console

FMD-273: enable performance insights on db instance

---

README.md
db/migrations/alembic.ini
db/migrations/env.py

Update how alembic migration filenames and revision IDs are generated so it's handled more consistently and automatically.

Alembic migration file format

---

core/db/queries.py

The outer joins in the `query_extend_with_region_filter` are actually redundant and only needed if these joins were directly incorporated into the base query, rather than conditionally extending the base query if one or more itl1 regions are passed to `download_data_base_query` (at which point we'll be filtering on regions and any projects without postcodes will be filtered out of the results anyway).

FMD-241: Remove outer joins from extended region filter query

---

core/controllers/mappings.py

Improve ```map_data_to_models``` docstring.

BAU: improve mapping docstring

---

core/controllers/download.py
core/table_extraction/process.py
core/transformation/pathfinders/pf_transform_r1.py
core/transformation/towns_fund/tf_transform_r3.py
core/validation/towns_fund/fund_specific_validation/fs_validate_r4.py
tests/db_tests/test_queries.py
tests/integration_tests/test_ingest_db_transactions.py
tests/transformation_tests/pathfinders/test_pf_transform_r1.py
tests/transformation_tests/towns_fund/test_tf_transform_r3.py
tests/validation_tests/pathfinders/cross_table_validation_tests/test_ct_validate_r1.py

Ticket SMD-730. 
_Fix some of the pytest warnings._
_Are tests passing? Then it works!_

Smd 730/address pytest warnings

---

db/migrations/.current-alembic-head
db/migrations/versions/037_drop_submission_reporting_ro.py

Final migration clearing up the column from the DB now that it's no longer used anywhere in code.

Drop `submission.reporting_round` from DB

---

copilot/data-store/addons/data-store-find-data.yml

https://dluhcdigital.atlassian.net/browse/FPASF-321

Expire find data download files after 7 days

---

core/controllers/async_download.py
openapi/api.yml
tests/integration_tests/test_async_download.py

Ticket:
https://dluhcdigital.atlassian.net/browse/FPASF-102
Description:
Changing trigger_async_download endpoint and OpenAPI definition from "GET" to "POST" method.

Async download

---

core/controllers/async_download.py

https://dluhcdigital.atlassian.net/browse/FPASF-153
Each time a user downloads the file, a new presigned URL is generated. The availability of the presigned URL is set to a
short duration.

validate presigned url to for 30 seconds

---

config/envs/development.py

Remove version1.com domains

---

README.md
data_store/cli.py
data_store/controllers/get_filters.py
data_store/util.py
tests/data_store_tests/controller_tests/test_filters.py

Two changes:
1. Make filter functions return empty lists or None if no data is found. Now it's throwing exceptions.
2. Make seeder also insert example data
```bash
docker compose down
docker compose up
Does it work?

Make Find work without data

---

.github/workflows/aws_copilot_deployment.yml
.github/workflows/deploy_combined_service.yml
.github/workflows/deployment_cd_test_prod.yml

Shorten workflow job names and add specific names for readability.

BAU: Shorten workflow job names for readability

---

db/migrations/env.py

File
"/Users/sam/work/dluhc/funding/funding-service-design-post-award-data-store/db/migrations/env.py", line 94, in process_revision_directives
migration_script = directives[0]
~~~~~~~~~~^^^
IndexError: list index out of range

Fix migrations if zero schema changes

---

README.md

Update to reflect new workflow URLs and process.
Readme documentation should make sense

Update readme deployment info

---

scripts/migration-task-script.py

Fix script typo

---

.github/workflows/test.yml

Test postgres version should reflect the running version
Tests should still pass

BAU: Update test postgres version

---

.github/workflows/aws_copilot_deployment.yml

`fail-fast` in this context means "if one of the matrix jobs fails, cancel all of the other ones in progress". This could leave us in an unexpectedly inconsistent state (aware that if one fails we'll be in an inconsistent state, but at least a more understandable one).

Don't fail fast these matrix deployments

---

.pre-commit-config.yaml

Enable `mypy` checks for `submit` and `find` directory.
Is `mypy` check passing?

FPASF-547 and FPASF-548: Enable mypy on submit and find directory

---

pyproject.toml

We'll slowly work to turn all of these on.

Add strict mypy flags (disabled)

---

pyproject.toml

Enable warn_unused_configs mypy config
Is mypy check passing?

FPASF-554: Enable warn_unused_configs mypy config

---

pyproject.toml

Enable warn_redundant_casts mypy config
Is mypy check passing?

FPASF-555: Enable warn_redundant_casts mypy config

---

.pre-commit-config.yaml
data_store/controllers/ingest.py
data_store/controllers/ingest_dependencies.py
data_store/controllers/load_functions.py
data_store/table_extraction/extract.py
data_store/transformation/pathfinders/pf_transform_r1.py
data_store/transformation/towns_fund/tf_transform_r3.py
data_store/transformation/utils.py
data_store/validation/__init__.py
data_store/validation/initial_validation/checks.py
data_store/validation/initial_validation/initial_validate.py
data_store/validation/towns_fund/schema_validation/casting.py
data_store/validation/towns_fund/schema_validation/validate.py
db/migrations/env.py
pyproject.toml
requirements-dev.in
requirements-dev.txt
requirements.in
scripts/db_filename_clean.py
scripts/validate.py

Enable warn_redundant_ignores mypy config
Is `mypy` check passing?

FPASF-556: Enable warn_redundant_ignores mypy config

---

data_store/transformation/utils.py
pyproject.toml

Enable strict_equality
Is `mypy` check passing?

FPASF-557: Enable strict_equality

---

tests/e2e_tests/conftest.py

Playwright lets you read messages sent to the JavaScript console, as well as the level they're written at (eg info, warning, error).
Let's capture errors and raise those in pytest as warnings, which will get caught and report as test failures.
This should help us catch anything broken client-side, for example if a script fails to load because of a CSP violation.
* Run the e2e tests (`pytest --e2e`) - they should pass
* Comment out the line `content_security_policy_nonce_in=["script-src"]` in `app.py`
* Re-run the e2e tests - you should get a pytest error reporting that CSP has blocked script execution.

Report browser console errors

---

data_store/db/queries.py
data_store/messaging/messaging.py
data_store/messaging/tf_messaging.py
pyproject.toml
tests/data_store_tests/messaging_tests/test_tf_messaging.py

Remove mypy file exceptions:
- `data_store.messaging.messaging`
- `data_store/db/queries exception`
- `data_store.messaging.tf_messaging`
Are tests passing?
Is mypy happy?

Remove mypy exceptions part 2

---

data_store/cli.py
tests/integration_tests/test_ingest_component_towns_fund.py
tests/integration_tests/test_ingest_db_transactions.py

https://dluhcdigital.atlassian.net/browse/FPASF-493
Missed a few references in tests :)

Clean up programme_junction.reporting_round, and validation command

---

tests/integration_tests/test_ingest_component_pathfinders.py

One more reference to programme_junction.reporting_round

---

data_store/db/entities.py
db/migrations/versions/043_non_nullable_reporting_round.py

https://dluhcdigital.atlassian.net/browse/FPASF-494
This field should always be populated now.

Make reporting round FKs non-nullable

---

.github/workflows/test.yml
db/migrations/.current-alembic-head

I missed this in the last PR :(

Pin current alembic head for migrations

---

data_store/table_extraction/extract.py
data_store/table_extraction/process.py
data_store/util.py
data_store/validation/pathfinders/cross_table_validation/common.py
pyproject.toml
tests/data_store_tests/table_extraction_tests/test_extract.py
tests/data_store_tests/validation_tests/pathfinders/schema_validation_tests/test_pf_schema_validate.py

Remove mypy exceptions from files:
- data_store.util 
- scripts.validate
- schema_validation_tests/test_pf_schema_validate
- table_extraction/extract 
- pathfinders/test_pf_transform_r1
- data_store/table_extraction/process
Is `mypy` check passing?
Is `pytest` check passing?

Remove mypy exceptions part 3

---

copilot/post-award/manifest.yml

As the expensive operations have now been offloaded to celery we can reduce the CPU and memory of this service.
Should still work after deployment!

BAU: Reduce CPU and memory

---

db/migrations/.current-alembic-head
db/migrations/versions/044_remove_old_rr_cols.py

https://dluhcdigital.atlassian.net/browse/FPASF-494
Once https://github.com/communitiesuk/funding-service-design-post-award-data-store/pull/730 has gone in, no code is using the old columns - so let's remove them 🎉

Fpasf 494/remove old reporting round cols migration

---

data_store/transformation/pathfinders/pf_transform_r1.py
data_store/transformation/towns_fund/tf_transform_r3.py
data_store/validation/__init__.py
data_store/validation/pathfinders/cross_table_validation/common.py
data_store/validation/pathfinders/cross_table_validation/ct_validate_r1.py
data_store/validation/towns_fund/failures/user.py
data_store/validation/towns_fund/fund_specific_validation/fs_validate_r4.py
data_store/validation/towns_fund/schema_validation/validate.py
pyproject.toml
pytest.ini

Rest of the files. With few exceptions left behind.
Is mypy and pytest happy?

Remove mypy exceptions part 4

---

data_store/controllers/async_download.py
data_store/controllers/ingest.py
data_store/db/utils.py
find/main/routes.py
submit/__init__.py
submit/main/decorators.py
submit/main/routes.py

Ticket:
https://dluhcdigital.atlassian.net/browse/FPASF-538
Description:
We want to remove any secrets from logging and also ensure that only basic, immutable data types are being logged.

Remove secrets & large objects from logging

---

requirements-dev.in
requirements-dev.txt

Reverts communitiesuk/funding-service-design-post-award-data-store#750

Revert "Add watchdog for celery auto refresh"

---

requirements-dev.in
requirements-dev.txt

Add watchfiles dev dependency.
Use docker runner pr to test

Add watchfiles dev dependency

---

admin/base.py

I made this more complicated than it needs to be.
All of our authorization checks still pass.

Simplify admin auth

---

scripts/restore-sanitised-database.sh

Issue spotted while running script, restore path did not match
Have tested locally

BAU: fix restore path

---

tests/e2e_tests/conftest.py

Use HTTPS for local end-to-end tests

---

admin/__init__.py
admin/entities.py
app.py
tests/admin_tests/test_auth.py

Adds a readonly admin view for viewing ProjectProgress entries.

Add project progress admin view

---

README.md
data_store/cli.py
scripts/restore-sanitised-database.sh

I created a Flask CLI command that allows you to restore a sanitised database directly from the production bucket to your local database. I also added a help function and included named arguments for better usability.

Restore sanitised db using flask cli

---

scripts/sanitise-db.sql
scripts/sanitise-post-award-database.sh

- This PR updates the sanitisation script to apply it to all new tables.
- Added checks to ensure the PostgreSQL version meets the requirements for restoring the database.
- Updated the script to accept random int between start and end int

Adding new tables to sanitise script

---

requirements-dev.in
requirements-dev.txt

https://github.com/microsoft/debugpy/pull/1657

Bump debugpy to fix hot reloading with debugger

---

db/migrations/.current-alembic-head
db/migrations/versions/048_validate_check_constraints.py

Sits on top of https://github.com/communitiesuk/funding-service-design-post-award-data-store/pull/523
Following on from the patches where we added this constraint to prevent
further bad data getting into the DB.
We will fix the existing bad data, and once that's done we can validate
this constraint to make sure it's in place for all data in the table
(not just new data entering).
- Deploy to dev (making sure dev has a representative clean copy of data from prod).

FMD-268: validate the constraints

---

scripts/sanitise-post-award-database.sh

* Stop the script if any command fails
* Make sure user is inside the `scripts` directory, as this is expected elsewhere.
* Fix a broken `if` statement (missing an exit and an end).
* Fix the `read` command to not exit with status 1.
* Move postgresql_anonymizer cloning before the DB cluster setup step so that if it fails we don't waste a load of time.

Small script fixes

---

.vscode/launch.json

For the combined docker runner, the debugging port for data-store has been updated: https://github.com/communitiesuk/funding-service-design-docker-runner/pull/71

Update vscode debugging port for combined docker runner

---

copilot/download-report/overrides/cfn.patches.yml

Remove unneeded permission post migration
Job should still deploy and run

FPASF-409: Remove unneeded permission post migration

---

data_store/validation/pathfinders/cross_table_validation/common.py

Missed one when I did this: https://github.com/communitiesuk/funding-service-design-post-award-data-store/pull/858

Froce str for allowed_values_key

---

scripts/restore-sanitised-database.sh

Previously the docker lookup was failing with the combined docker runner, and would continue running following a failure of one step
Should be able to run `scripts/restore-sanitised-database.sh --restore-to-local-db` successfully (if docker container running)

BAU: change docker database lookup method and add more error handling

---

admin/entities.py
admin/templates/admin/edit_organisation.html
tests/admin_tests/test_actions.py
tests/admin_tests/test_auth.py
tests/conftest.py

Ticket:
https://mhclgdigital.atlassian.net.mcas.ms/browse/FPASF-609
Description:
This PR allows editing of an organisation's external_reference_code in the admin view.

Editing external_reference_code

---

config/envs/default.py

Use new service desk URL 
Link 'Submit a request for help' should go to new URL

BAU: Update Service Desk URL

---

app.py
config/envs/default.py
config/envs/development.py

Refactor how Flask-Debugtoolbar is setup. @wjrm500 [very sensibly suggested the CSP stuff should be in our config classes instead](https://github.com/communitiesuk/funding-service-design-fund-application-builder/pull/207), so I've moved it there.

Move CSP config for debugtoolbar to config classes

---

find/main/routes.py
tests/admin_tests/test_auth.py
tests/find_tests/test_routes.py

https://mhclgdigital.atlassian.net/browse/FLS-928
It should fix the [sentry]([https://funding-service-design-team-dl.sentry.io/issues/6223252656/?environment=prod&query=is%3Aunresolved issue.priority%3A[high%2C medium]&referrer=issue-stream&statsPeriod=14d&stream_index=0](https://funding-service-design-team-dl.sentry.io/issues/6223252656/?environment=prod&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0))  error.

Fls 928 find download bug

---

copilot/download-report/overrides/cfn.patches.yml

https://mhclgdigital.atlassian.net/browse/FLS-1038
Allow data-store access to pre-award and form-adapter logs.

FLS-1038: Give permissions to Pre-award and Form-Runner-Adapter logs

---

copilot/post-award/manifest.yml

Fix after #935 
Sign in should work on post-award dev after deployment

FSPT-228: Fix authenticator communities hostname

---

copilot/post-award/manifest.yml

Fix for deployment error in: https://github.com/communitiesuk/funding-service-design-post-award-data-store/actions/runs/13719178394/job/38370796681
Should deploy to test successfully post-merge

FSPT-228: remove duplicate authenticator key

---

copilot/post-award-celery/manifest.yml
copilot/post-award/manifest.yml

Bug fix after #949, forgot these from the manifest changes!
Find and Submit should resolve on communities test domain after deployment

FSPT-228: update config for post award manifest

---

copilot/post-award-celery/manifest.yml
copilot/post-award/manifest.yml

Use production communities domain names environment variables
Should resolve at communities production domain post-deployment

FSPT-228: use production communities domains

---

config/envs/development.py

Description:
Update local config file with new Pathfinders and Towns Fund rounds

Update local config
